thirdweb-dev/web3-onboard

- src/modules/ready/balance.js
> Fix minimum balance comparison

- src/modules/ready/balance.js
- src/modules/select/wallets/dapper.js
- src/modules/select/wallets/fortmatic.js
- src/modules/select/wallets/portis.js
- src/utilities.js
> Pass 10 in to the toString method to avoid exponent notation

- src/components/ModalHeader.svelte
> Remove styling affecting dark mode heading color

- README.md
- src/modules/select/index.js
- src/modules/select/wallets/fortmatic.js
- src/modules/select/wallets/portis.js
- src/utilities.js
This PR fixes the problems with network initialization of the sdk wallet modules.
> Fix wallet module initialization network

- src/@types/libraries.d.ts
- src/onboard.ts
- src/stores.ts
Set initial state to null and don't call subscription callback unless not null
> Subscription Initial State

- src/interfaces.ts
- src/stores.ts
- src/utilities.ts
- yarn.lock
> Refine the wallet reset functionality

- src/modules/select/wallets/authereum.ts
> update authereum url depending on network

- src/modules/select/wallet-icons/icon-squarelink.ts
- src/modules/select/wallet-icons/icon-torus.ts
> Fix icon heights

- package.json
- src/interfaces.ts
- src/modules/select/wallets/torus.ts
- src/utilities.ts
- src/validation.ts
- yarn.lock
- bump version
- add support for enabled verifiers
> Torus integration

- package.json
- src/modules/select/wallets/wallet-connect.ts
- yarn.lock
This PR updates the WalletConnect dependency to version `1.0.5` which features support for mobile to mobile connection. The WalletConnect wallet module has been updated so that it can be selected on mobile devices.
> Feature: Update WalletConnect

- src/modules/select/wallets/ledger.ts
- src/modules/select/wallets/trezor.ts
This PR partly fixes #382. The Ledger transport doesn't seem to fire an event for when the user disconnects their device. The code is implemented to handle that event if it gets fired in the same way that it does for the Electron Ledger Transport. An issue has been raised on the repo and will upgrade if a fix is released.
Issue can be found here: https://github.com/LedgerHQ/ledgerjs/issues/510
> Fix: Hardware Wallet Reset

- src/interfaces.ts
- src/modules/select/index.ts
- src/modules/select/wallets/imtoken.ts
- src/modules/select/wallets/mykey.ts
- src/modules/select/wallets/trust.ts
- src/utilities.ts
> Fix: Mykey balance

- src/modules/select/wallets/trust.ts
> Fix: Trust Provider

- package.json
- rollup.config.js
- src/@types/index.d.ts
- src/interfaces.ts
- src/modules/select/wallets/ledger.ts
- src/onboard.ts
- src/utilities.ts
- src/views/WalletSelect.svelte
- yarn.lock
> Enhancement: Ledger Transport

- package.json
- rollup.config.js
- src/@types/index.d.ts
- src/modules/select/wallets/ledger.ts
- yarn.lock
This PR reverts the changes made to the Ledger transport in #424
> Fix: Ledger U2F Revert

- src/modules/select/wallets/trezor.ts
This PR ensures that all heavy dependencies that are needed for the Trezor provided are dynamically imported to avoid wasted bandwidth.
> Enhancement: Trezor code split

- src/utilities.ts
- Updates MetaMask module to be compatible with upcoming updates.
> Enhancement: MetaMask update

- src/modules/select/wallets/metamask.ts
- Adds a deep link for MetaMask rather than just linking to their homepage
> Add MetaMask deep link

- src/modules/select/index.ts
- src/modules/select/wallet-icons/icon-dcent.ts
- src/modules/select/wallets/dcent.ts
- src/utilities.ts
- Support D'CENT Wallet mobile app
> add D'CENT Wallet

- package.json
- yarn.lock
> lock torus version 1.8.2

- src/interfaces.ts
- src/modules/select/wallets/providerEngine.ts
- src/modules/select/wallets/wallet-connect.ts
- src/onboard.ts
- src/stores.ts
- src/validation.ts
> blockPollingInterval add

- package.json
- src/interfaces.ts
- src/modules/select/wallets/status.ts
- src/utilities.ts
This PR:
- Modifies the Status wallet interface so that is checks if account access has been approved before requesting accounts
- Refactors the `connect` function on the modern provider interface to be more readable
- Removes some unnecessary commas on a TypeScript interface
> 1.19.0-0.0.1: [fix] - Status Wallet Module

- package.json
> Release 1.19.1

- package.json
- src/services.ts
> 1.19.1-0.0.1: [fix] - Optional dappid

- package.json
- src/services.ts
1.19.1-0.0.1: [fix] - Optional dappid (#497)
> Release 1.19.2

- package.json
> Version 1.19.2

- .prettierrc.js
- package.json
- src/components/SelectedWallet.svelte
- src/interfaces.ts
- src/modules/select/content.ts
- src/modules/select/index.ts
- src/modules/select/wallets/metamask.ts
- src/views/WalletSelect.svelte
> 1.20.0-0.0.1: [enhancement] - Install Wallet Copy

- package.json
> Version 1.21.0

- package.json
- src/interfaces.ts
> Release 1.22.0

- package.json
- src/stores.ts
- src/utilities.ts
- yarn.lock
- Filters SDK events to just receive confirmed status event for efficient balance updates
Closes #526
> 1.22.0-0.2.0: [enhancement] - Filter Confirmed Status

- package.json
> Version 1.23.0

- package.json
- src/components/Wallets.svelte
- src/constants.ts
- src/elements/Button.svelte
- src/elements/IconButton.svelte
- src/interfaces.ts
- src/modules/index.ts
- src/onboard.ts
- src/stores.ts
- src/validation.ts
- src/views/WalletSelect.svelte
> 1.23.0-0.1.0: [feature] Adds optional terms agreement

- package.json
- src/components/Wallets.svelte
- src/constants.ts
- src/elements/Button.svelte
- src/interfaces.ts
- src/modules/check/network.ts
- src/modules/index.ts
- src/modules/select/wallets/cobovault.ts
- src/modules/select/wallets/lattice.ts
- src/onboard.ts
- src/stores.ts
- src/validation.ts
- src/views/WalletCheck.svelte
- src/views/WalletSelect.svelte
*  Fixes termsAgreed getting set on init w/o config being set
* Adds classnames for customization of tos agreement
> 1.23.0-0.2.1: [fix] Terms of service

- package.json
- src/modules/select/wallet-icons/icon-coinbase.ts
- src/modules/select/wallets/coinbase.ts
- src/modules/select/wallets/wallet-link.ts
- yarn.lock
This PR updates WalletLink to the latest version (2.1.0) and updates the Coinbase Wallet icon
New icon:
> Update WalletLink to 2.1.0 and updates the Coinbase Wallet icon

- package.json
- src/modules/select/wallets/wallet-connect.ts
> 1.25.0-0.5.5: [fix] Add check for WalletConnect Initialization object

- package.json
- src/stores.ts
- src/views/WalletSelect.svelte
Resolves #500 
Example:
```ts
const config = {
//... other config options
subscriptions: {
wallet: wallet => {
const { svg, iconSrc, iconSrcSet } =  wallet.icon
}
}
}
const onboard = Onboard(config)
```
> 1.26.1-0.1.0: [feature] Export wallet icons

- package.json
- src/onboard.ts
- Adds convenient server side rendering support
Closes #569
> 1.26.2-0.1.0: [enhancement] - SSR Support

- package.json
- src/interfaces.ts
- src/modules/select/wallets/torus.ts
- src/onboard.ts
- src/stores.ts
- src/views/WalletSelect.svelte
- yarn.lock
- 1.26.1-0.1.0: [feature] Export wallet icons (#572)
- 1.26.2-0.1.0: [enhancement] - SSR Support (#570)
- Bump browserslist from 4.13.0 to 4.16.6 (#563)
- 1.26.1-0.0.1: [chore] Update Wallet type (#574)
> Release 1.27.0

- src/modules/select/wallets/hd-wallet.ts
- src/views/WalletSelect.svelte
Tried to make possible to use multi-digit numbers in derivation path: `m/44'/60'/12'/0/0`
> Fix derivation path validation

- package.json
- src/views/WalletSelect.svelte
- Fixes TypeScript error by initializing variable whilst also keeping functionality the same
> 1.28.0-0.1.1: [fix] - Agreed Type

- package.json
- src/interfaces.ts
- src/modules/check/network.ts
- src/onboard.ts
- src/views/Onboard.svelte
- src/views/WalletCheck.svelte
- Fixes switch wallet flow so that it also includes a call to `walletCheck` to complete the full flow
> 1.28.0-0.2.1: [fix] - Switch Wallet Flow

- package.json
> Release 1.29.0

- package.json
- src/modules/select/wallets/keepkey/entryModal.ts
- src/modules/select/wallets/keepkey/index.ts
- src/views/WalletCheck.svelte
- Switches CTA buttons i.e. **Connect**, **Dismiss** such that cancel buttons are on the left
- Adds preferred to Keepkey
- Allows for enter button to submit pin/passphrase
Fixes #596
> 1.29.0-0.2.0: [fix] Keepkey issues

- package.json
- yarn.lock
> Release 1.30.0

- package.json
- src/modules/select/index.ts
Onboard will now support injected wallets by default.
Addresses #605
> 1.29.0-0.5.5: [refactor] detected wallet

- package.json
- src/modules/select/index.ts
- src/utilities.ts
> 1.29.0-0.5.9: Fix ens on non-ethereum networks - filter out detectedwallet

- package.json
- src/modules/select/wallets/trezor.ts
> 1.29.0-0.5.10: Fix Trezor txn sign issue

- package.json
- yarn.lock
fixes server load issues
from walletconnect: https://twitter.com/WalletConnect/status/1419999849068564505
> 1.31.0-0.0.1: [update] bump walletconnect - 1.5.0

- package.json
- yarn.lock
> 1.31.0-0.0.5: [update] walletconnect v1.5.2

- package.json
- src/modules/check/network.ts
> 1.33.0-0.0.1: [fix] Fixes walletconnect hanging on network check

- package.json
- src/modules/select/wallets/keystone.ts
- yarn.lock
Port from #656
---
This PR fixed several UI and logic bugs in Keystone.
> 1.33.0-0.2.2: [fix] keystone bugs

- package.json
- yarn.lock
Big perf improvements in the latest WC version
announcement here: https://twitter.com/WalletConnect/status/1426226788515078144?s=20
> bump walletconnect 1.6.0

- package.json
Includes critical update for walletconnect
> Release: 1.34.1 - Develop

- package.json
- src/modules/select/wallets/keystone.ts
> 1.34.1-0.1.2: [fix] keystone accounts

- package.json
- src/utilities.ts
> 1.34.2-0.0.1: [chore] Add boba chain

- package.json
- yarn.lock
Update walletlink to 2.1.10 in which we've added support for addEthereumChain and switchEthereumChain requests.
> 1.34.2-0.0.2:[update] walletlink to 2.1.10

- package.json
- src/utilities.ts
Fixes an issues where we event listeners on the provider where not properly cleaned up. This result in some weird behaviors as described in #681.
> 1.34.2-0.0.5: [fix] Dangling event listeners

- .circleci/config.yml
- package.json
- yarn.lock
Includes an update to keystone that should fix build issues for our users.
Addresses #702
> 1.34.2-0.0.7: [update] Latest Keystone update to fix builds

- package.json
- src/modules/select/index.ts
- src/modules/select/wallets/detectedwallet.ts
- src/utilities.ts
- refactors detection to include builtin wallets
- removes unused providers
Addresses #600 and #697
> 1.34.2-0.0.8: [fix] EIP-1193 support in onboard

- package.json
- yarn.lock
There seems to be an issue that was introduced after v0.7.7 -- reverting back until the issue is resolved
> 1.34.2-0.0.9: [chore] Revert Keystone back to v0.7.7

- package.json
Fix #691 
Need an M1 macer to test
> 1.35.0-0.0.1: [fix] Make mew wallet an optional dep

- package.json
- yarn.lock
Updates ledger deps to enable EIP-1559 signing with ledger
> 1.35.0-0.0.2: [update] Update ledger deps

- package.json
- src/modules/select/wallets/keystone.ts
- yarn.lock
Fix the bug that keystone wallet throws error after sync wallet QR code
> [fix]: 1.35.1-0.0.1 - Keystone Wallet Import Accounts Bug

- package.json
> Release 1.35.2

- package.json
> Release: 1.35.3 - Develop

- package.json
- yarn.lock
Updating walletlink to latest release. 
Fixes this known issue: https://github.com/walletlink/walletlink/issues/149
> fix: Update walletlink to 2.2.6 to fix bug

- .circleci/config.yml
@aaronbarnardsound 
I modified the config per [this](https://johnclarke73.medium.com/publishing-to-npm-using-circleci-b9dc8dfd718a) tutorial.
> This fixes publishing to npm

- .circleci/config.yml
> Fix NPM Publish Error

- packages/demo/src/App.svelte
- `eth_sign`
- `eth_signTransaction`
- `eth_signTypedData` - under the hood this will use the v3 of signing typed messages
> Add signing to Demo project - O2

- packages/common/src/views/AccountSelect.svelte
Add transition to modal, give more space to the network dropdown
> Add transition to modal, give more space to the network dropdown

- package.json
> Release: 1.37.1 - Develop

- packages/core/src/views/connect/Index.svelte
- packages/demo/webpack.config.js
- packages/trezor/src/index.ts
Fixes Trezor error by adding process in the provide plugin and then accessing nested default on Trezor module.
> Test fix for Trezor

- packages/core/README.md
- packages/core/src/utils.ts
- packages/core/src/views/connect/Sidebar.svelte
- packages/core/src/views/shared/WalletAppBadge.svelte
- Adds options to pass in image URL for app metadata icon
> Adds option to use image URL for icon

- package.json
1.38.1 Release : Develop - New branding
> 1.38.1 Release : Develop - New branding

- package.json
> 1.38.2 Release - Develop

- packages/react/README.md
- packages/react/src/index.ts
Update docs to include info for disconnect method
> Update docs to include info for disconnect method

- packages/core/package.json
- packages/core/src/index.ts
- packages/react/package.json
- packages/react/src/index.ts
- Exports `DisconnectOptions` type from `core`
- Updates React hooks so that wallet is reactive
- Fixes React hooks unsubscribe calls
> Fix: Connect wallet hook

- packages/core/README.md
Update core docs with more chains and a link to the react hooks package in case they are using react
> Update core docs

- packages/core/README.md
- Fixes typo that broke the link to build environments in the readme
> Fix link to build environments in readme

- packages/core/src/provider.ts
- packages/core/src/types.ts
- Adds missing `avatar` property to ENS object
> core-v2.0.6: [fix] - Add Avatar to ENS Object

- packages/core/src/views/connect/Index.svelte
- Modify render logic to not render `InstallWallet` component if autoSelecting a wallet
> core-v2.0.6: [fix] - Disable Install Wallet Component

- packages/core/package.json
- Fixes ENS object missing avatar
- Fixes rendering of install wallet component when auto selecting a wallet
> Release Core 2.0.6

- packages/core/package.json
- packages/core/src/provider.ts
- Fixes a bug where there was a missing check to ensure there is a chain rpcUrl for ENS lookups
Closes #870
> core/v2.0.8: [fix] - Check Before ENS Lookup

- packages/fortmatic/package.json
- packages/fortmatic/src/index.ts
- packages/torus/package.json
- packages/torus/src/index.ts
- Fixes bugs where calls to `parseInt` of hex strings were incorrectly passing in the value `10` for the radix.
Closes #872
> [fix] parseInt Calls

- packages/core/README.md
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/views/shared/Modal.svelte
- Adds a CSS var for all modal `z-index` values
> Add modals z-index

- packages/react/package.json
> Update deps for react package

- package.json
- packages/ledger/package.json
- packages/ledger/src/index.ts
> [refactor]: Alternative method of address generation for Ledger

- packages/keystone/src/index.ts
- packages/keystone/tsconfig.json
- Turns strict type checking off until Keystone types are fixed
- Removes type for provider request
> [fix]: Works around bad Keystone types

- packages/demo/package.json
- packages/demo/src/App.svelte
Followup per https://github.com/blocknative/web3-onboard/pull/904#issuecomment-1089583249
> [update] Coinbase Wallet demo

- packages/react/package.json
> [react-v2.1.5] - version update for publish

- packages/core/README.md
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/views/connect/Sidebar.svelte
- packages/core/src/views/connect/WalletButton.svelte
- packages/core/src/views/shared/Modal.svelte
Expose css variables for the following:
- border-radius for the wallet connect modal & wallet buttons
- shadows for the wallet connect modal & wallet buttons
- the backdrop for the wallet connect modal to control color and opacity
This handles issue #960
> [core-v2.2.6] : Enhancement - CSS variable add

- packages/keepkey/package.json
- packages/keepkey/src/index.ts
> Fixes type issue with keepkey

- packages/demo/src/App.svelte
- packages/ledger/package.json
- packages/ledger/src/index.ts
There was an issue with signing messages in ledger where the recovered address didn't match the signing address. Just needed to remove the hex prefix before signing.
> [fix]: Fixes signing issue with ledger

- README.md
> fixed a typo with the git branch

- packages/common/package.json
- packages/common/src/types.ts
- packages/core/src/validation.ts
- packages/injected/README.md
- packages/injected/package.json
- packages/injected/src/validation.ts
> Fixes misc validation and types.

- packages/coinbase/package.json
- packages/coinbase/src/index.ts
- packages/injected/package.json
- packages/injected/src/types.ts
> [fix] Duplicate coinbase wallets

- packages/core/package.json
- packages/core/src/views/account-center/Index.svelte
> [fix] Remove unnecessary state updates

- packages/coinbase/package.json
- packages/coinbase/src/index.ts
- packages/common/package.json
- packages/common/src/types.ts
Fixes a type and build issue that was introduced in the last release.
> [fix] Fixes a type & build issue

- packages/core/package.json
- packages/core/src/views/account-center/Index.svelte
- packages/react/package.json
Styling update to make the account center persistent on the screen as the user scrolls.
> Fix absolute bug

- packages/injected/package.json
- packages/injected/src/wallets.ts
- yarn.lock
This PR updates how the Coinbase injected wallet handles the Coinbase App provider by check at the top level for the CoinbaseExtension flag rather then within the providers array.
Tested on Desktop and Coinbase Wallet App using NGROK
> [injected-wallets] : update - Coinbase app provider handling by coinbase injected wallet

- packages/core/package.json
Release - Syncs develop branch
> Release: 06-02 (develop)

- .circleci/config.yml
> Update circleci to include vue package

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/views/connect/Index.svelte
Set inProgress to false if connection error.
Fix for #1032
> [fix] fix connect wallet with disableModal flag

- packages/core/src/views/account-center/Maximized.svelte
- packages/core/src/views/connect/WalletButton.svelte
- packages/demo/src/App.svelte
- packages/react/package.json
- yarn.lock
> [core-v2.2.11-alpha.3]: enhancement - add border-radius CSS variables

- packages/core/package.json
- packages/core/src/views/account-center/Maximized.svelte
- packages/core/src/views/connect/WalletButton.svelte
- packages/demo/src/App.svelte
- packages/react/package.json
- yarn.lock
Bump core package version to v2.2.11-alpha.3
> [core-v2.2.11-alpha.3]: Fix - core package bump

- packages/react/package.json
> [react-v2.1.8-alpha.3]: Fix - react version bump

- packages/demo/src/App.svelte
- packages/web3auth/README.md
> Adds docs for web3auth

- packages/react/package.json
Update Core and Common package versions within the react package to the latest develop versions
> [react-v2.1.9-alpha.1] : Update - React package deps update

- packages/react/package.json
React package deps - Fix common version
> [react-v2.1.9-alpha.1] : Update - React package deps - Fix common version

- package.json
Release PR to establish our semantic versioning at the base repo level.
> Release: 2.0.2 (main)

- package.json
- yarn.lock
Run yarn and remove path extra on packages within workspaces at top level package.json
> [web3-onboard-v2.3.0-alpha.1] : Fix - Notifications build issue

- README.md
- packages/core/README.md
- packages/react/README.md
- packages/vue/README.md
Modifies docs for Core, React and Vue packages so that the quick-start sections have the minimal code necessary to get up and running and also adds examples of how to create and Ethers provider with the connected wallet.
> [docs]: Simplify Quickstart

- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/walletconnect/README.md
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
> [walletconnect-v2.0.4-alpha.2] : Feature - Connect First ChainId on WalletConnect session request

- .prettierignore
- packages/coinbase/package.json
- packages/common/package.json
- packages/common/src/hdwallets.ts
- packages/common/src/index.ts
- packages/common/src/types.ts
- packages/core/package.json
- packages/core/src/types.ts
- packages/dcent/package.json
- packages/demo/src/App.svelte
- packages/fortmatic/package.json
- packages/gnosis/package.json
- packages/injected/package.json
- packages/keepkey/package.json
- packages/keystone/package.json
- packages/ledger/package.json
- packages/ledger/src/index.ts
- packages/magic/package.json
- packages/mew/package.json
- packages/portis/package.json
- packages/react/package.json
- packages/torus/package.json
- packages/trezor/package.json
- packages/vue/package.json
- packages/walletconnect/package.json
- packages/walletlink/package.json
- packages/web3auth/package.json
> Fixes ledger transaction on polygon

- README.md
> added tagline

- packages/react/package.json
- packages/vue/package.json
Update Core version in Vue & React packages
> Update Core version in Vue & React packages

- packages/walletconnect/README.md
> fix(Doc): typo in WalletConnect sdk readme example

- packages/core/package.json
- packages/gas/package.json
> gas-v2.0.0-alpha.1, core-v2.6.0-alpha.6]: Fix:  Trigger Gas Module Publish

- packages/injected/src/wallets.ts
> Tokenary support on all platforms

- packages/core/README.md
```onboard.state.actions.updateAccountCenter``` function takes settings object directly, no need for desktop/mobile wrapper otherwise error is thrown
> Fix readme example

- README.md
Added a link to the migration guide in the documentation: https://docs.blocknative.com/onboard/migration-guide
> [README Updates] Migration guide Link

- packages/core/package.json
- packages/core/src/index.ts
- packages/react/package.json
- packages/vue/package.json
Moves the check for re-initialization to the top of the function, so that the reset of state does not override new init options.
Fixes #1196
> Fix: Re-initialize Cleanup Logic

- docs/src/routes/docs/[...1]introduction/[...1]getting-started.md
- docs/src/routes/docs/[...1]introduction/[...3]onboard.js-migration-guide.md
- docs/src/routes/docs/[...3]packages/core.md
- docs/src/routes/docs/[...3]packages/injected.md
> intro final draft

- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Core package version fix to align package builds
> [core-v2.8.2-alpha.2] : Fix - Core package version

- packages/core/README.md
- packages/core/package.json
- packages/core/src/views/connect/WalletButton.svelte
- packages/react/package.json
- packages/vue/package.json
- yarn.lock
Add variable for wallet button text color & box shadow on hover
Fixes #1240
> [core-v2.8.3-alpha.1, react-v2.3.3-alpha.1, vue-v2.2.3-alpha.1] : Update - Add variable for wallet button text color & box shadow on hover

- packages/core/package.json
- packages/core/src/views/connect/Index.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Fixes  #1268 where border-radius in the top right of the header is set to a fixed `24px`
> Fixes Header border radius (#1268)

- packages/core/package.json
- packages/core/src/chain.ts
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
- yarn.lock
Fixes: #1257 
Upon network switch, if the chain is not available in the wallet(MM) the user is prompted to add the chain, if the user cancels this action the promise now resolves to false.
> [core-v2.8.5-alpha.1, react-v2.3.5-alpha.1, vue-v2.2.5-alpha.1] : Fix - Handle add new chain canceled by user

- package.json
- packages/coinbase/package.json
- packages/common/package.json
- packages/core/package.json
- packages/dcent/package.json
- packages/fortmatic/package.json
- packages/gas/package.json
- packages/gnosis/package.json
- packages/hw-common/package.json
- packages/injected/package.json
- packages/keepkey/package.json
- packages/keystone/package.json
- packages/ledger/package.json
- packages/magic/package.json
- packages/mew/package.json
- packages/portis/package.json
- packages/react/package.json
- packages/sequence/package.json
- packages/tallyho/package.json
- packages/torus/package.json
- packages/trezor/package.json
- packages/vue/package.json
- packages/walletconnect/package.json
- packages/walletlink/package.json
- packages/web3auth/package.json
- Updates homepage link in package.json file for all packages
Note: I did not do a version bump on the packages as they have all been bumped in develop via #1290 so no need to bump again.
> [chore] - Update homepage links

- docs/src/routes/examples/connect-wallet.md
> change title of example page

- package.json
- packages/core/package.json
- packages/demo/package.json
- Syncs develop branch versions
> Release 2.13.0 (develop)

- package.json
- packages/react/package.json
- packages/vue/package.json
- Updates core version in the Vue and React packages
> Release 2.13.1

- docs/src/routes/faq/index.md
added link to discord
tabbed over faq answers
> updated docs faq styling

- docs/src/routes/docs/[...1]overview/[...2]contribution-guide.md
> creating contribution guide

- docs/package.json
- docs/src/lib/components/install-code.md
- docs/src/routes/docs/[...2]getting-started/[...1]installation.md
- docs/src/routes/docs/[...4]packages/injected.md
> injected wallets doc fix

- package.json
- packages/gas/package.json
- packages/gnosis/package.json
- yarn.lock
- #1336 
- `@web3onboard/gas` **v2.1.4**
- `@web3onboard/gnosis` **v2.1.4**
> Release 2.14.1 (develop)

- docs/package.json
- docs/src/lib/components/ThemeCustomizer.svelte
- docs/src/lib/components/gas/Gas.svelte
- docs/src/lib/components/gas/GasCard.svelte
- docs/src/lib/components/gas/index.ts
- docs/src/lib/components/gas/types.ts
- docs/src/lib/components/index.ts
- docs/src/routes/docs/[...1]overview/[...2]contribution-guide.md
- docs/src/routes/docs/[...4]packages/coinbase.md
- docs/src/routes/docs/[...4]packages/gas.md
- docs/src/routes/docs/[...4]packages/gnosis.md
- docs/src/routes/docs/[...4]packages/react.md
- docs/svelte.config.js
- docs/tailwind.config.cjs
- docs/yarn.lock
- packages/gas/README.md
Add more examples to the Gas modules along with a gas comparison visualization to compare against RPC gas pricing
> Docs gas example

- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
- yarn.lock
- Adds support for walletconnect `wallet_switchEthereumChain`
- Handle chain ID returned as hex in some situations
- Closes #1313 & PR: #1351 
Before Fix: https://www.loom.com/share/25801628496448b6962c861d9178b5dd
After Fix: https://www.loom.com/share/c6f71389b0c7463ca582bb9b9ec348ce
> [walletConnect v2.2.0-alpha.1]: Fix - walletConnect support for wallet_switchEthereumChain method

- packages/core/package.json
- packages/core/src/views/account-center/Micro.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Fixes #1358
- [ x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
> Fix css var typo

- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
Previously after switching chains using W3O functions, the chain was only updated within the WC session and would not reflect in the connected wallet or be respected when sending a transaction.
> [walletConnect-v2.2.1-alpha.1]: Fix - WalletConnect switch chains handling during transaction

- packages/core/README.md
Update container el docs for proper usage
> Update container el docs

- docs/src/routes/docs/[...4]wallets/mew.md
> Update mewwallet path

- docs/src/routes/docs/[...4]wallets/mew.md
> Update mewwallet path (#1387)

- packages/core/package.json
> Add TP as devDep in Core

- package.json
- packages/coinbase/package.json
- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/sequence/package.json
- packages/transaction-preview/package.json
- packages/vue/package.json
- packages/walletconnect/package.json
- yarn.lock
- Sequence wallet init fix #1389 
- [walletConnect-v2.2.1-alpha.1]: Fix - WalletConnect switch chains handling during transaction #1380 
- [coinbase-v2.2.0-alpha.1]: Upgrade coinbase wallet sdk #1373 
- [coinbase-v2.1.4-alpha.1]: Fix - Coinbase default entry #1371 
- [transaction-preview: v2.0.0-alpha.1 , core: v2.11.0-alpha.1, react, vue]: Feature - Transaction Preview Package #1359 
- `@web3onboard/coinbase` **v2.2.0**
- `@web3onboard/core` **v2.11.0**
- `@web3onboard/react` **v2.5.0**
- `@web3onboard/sequence` **v2.0.4**
- `@web3onboard/transaction-preview` **v2.0.0**
- `@web3onboard/vue` **v2.4.0**
- `@web3onboard/walletconnect` **v2.2.1**
> Release 2.15.0 (develop)

- packages/core/README.md
- packages/core/package.json
- packages/core/src/views/connect/ActionRequired.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Added text color css vars to Action Req modal, bump versions, update readme for CRA building
Fixes:
> [core-v2.11.1-alpha.3, React, Vue]: Fix - Update README for CRA build, Added text color css vars to Action Req modal to align

- packages/core/package.json
- packages/core/src/views/connect/Index.svelte
- packages/core/src/views/connect/Sidebar.svelte
- packages/core/src/views/connect/WalletButton.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
> Return CSS vars to connecting wallet buttons

- package.json
- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Fix to return necessary CSS vars
> Release 2.16.1 (develop)

- examples/with-sveltekit/yarn.lock
- examples/with-vite-react/yarn.lock
- package.json
- packages/core/package.json
- packages/core/src/views/connect/Index.svelte
- packages/core/src/views/connect/WalletButton.svelte
- packages/demo/package.json
- packages/demo/yarn.lock
- packages/react/package.json
- packages/vue/package.json
- yarn.lock
Fix to return necessary CSS vars
> Release 2.16.1

- docs/src/routes/docs/[...2]getting-started/[...1]installation.md
- docs/src/routes/docs/[...4]wallets/ledger.md
- docs/src/routes/docs/[...4]wallets/phantom.md
- docs/src/routes/docs/[...4]wallets/zeal.md
- docs/yarn.lock
Update Ledger init options and add Zeal Wallet docs
> Update Ledger init options and add Zeal and Phantom Wallet docs

- packages/core/package.json
- packages/core/src/views/notify/Notification.svelte
- packages/react/package.json
- packages/vue/package.json
This PR fixes #1466 when the `autoDismiss` parameter was not functioning for an updated notification.
> Fix: Notification autodismiss

- packages/core/package.json
- packages/core/rollup.config.js
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
- yarn.lock
Potential fix for https://github.com/blocknative/web3-onboard/issues/1470
Mentioned no the original Reverse resolution PR here: https://github.com/blocknative/web3-onboard/pull/1410/files#r1073857746
> Unstoppable Domains Reverse Resolution Cleanup

- docs/src/routes/docs/[...1]overview/[...1]introduction.md
- docs/src/routes/docs/[...1]overview/[...3]onboard.js-migration-guide.md
- docs/src/routes/docs/[...2]getting-started/[...2]customization.md
- docs/src/routes/docs/[...3]modules/core.md
- docs/src/routes/docs/[...3]modules/react.md
> Fix: typos

- packages/demo/package.json
- packages/transaction-preview/package.json
- yarn.lock
Updates a missed version bump and dependency bump causing a build error
> Update sdk version for TP

- packages/walletconnect/README.md
Remove hardware to the first sentence
> Remove "hardware"

- packages/fortmatic/README.md
Remover `Ledger hardware wallet` and replace with `Formatic`
> Remove "Ledger" and add "Fortmatic"

- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
Bump Wallet Connect versions for Alpha package out of `canary`
> Bump Wallet Connect version for `alpha` package out of `canary`

- docs/package.json
- packages/core/package.json
- packages/core/src/views/Index.svelte
- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/react/package.json
- packages/transaction-preview/package.json
- packages/transaction-preview/src/views/Maximized.svelte
- packages/vue/package.json
Revert TP gasUsed addition until we can properly handle type2 transactions for gasUsed
> Hot fix : revert tp gasUsed addition

- package.json
- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/transaction-preview/package.json
- packages/vue/package.json
Hot fix : revert tp gasUsed addition for Type2 transactions #1537
> Release 2.20.2 (develop)

- README.md
> Added XDEFI to readme

- docs/yarn.lock
- packages/demo/package.json
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
Fix - Add .js file ext to walletconnect imports
Closes: #1558
> [walletconnect-v3.2.1-alpha.1]: Fix - Add .js file ext to walletconnect imports

- package.json
- packages/demo/package.json
- packages/walletconnect/package.json
- [walletconnect-v3.2.1-alpha.1]: Fix - Add .js file ext to walletconnect imports #1559 
- @web3-onboard/walletconnect: 3.2.1
> Release 2.20.4 (develop)

- .github/workflows/docs.yml
> Docs release sitemap

- packages/demo/package.json
- packages/walletconnect/package.json
Fix walletconnect package versioning
> Fix walletconnect package versioning

- docs/package.json
- docs/src/lib/services/onboard.js
- docs/src/routes/docs/[...3]modules/core.md
- packages/core/README.md
- packages/core/package.json
- packages/core/src/utils.ts
- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/react/package.json
- packages/vue/package.json
Add Sepolia testnet to native support(chain icon and background color - both point to the Eth mainnet values)
Closes #1598
> [core, react, vue]: Enhancement - Add Sepolia testnet

- docs/src/routes/docs/[...4]wallets/injected.md
> Fix broken link in docs

- packages/core/package.json
- packages/core/src/views/account-center/WalletRow.svelte
- packages/demo/package.json
- packages/hw-common/src/views/AccountSelect.svelte
- packages/react/package.json
- packages/vue/package.json
Add styling to hide scrollbar within Account Center balance and address across browsers.
Fixes issue reported in discord: https://discord.com/channels/542403978693050389/1050488289775321148/1093071043721179236
> Add styling to hide scrollbar within Account Center across browsers

- docs/src/routes/docs/[...3]modules/core.md
- docs/src/routes/docs/[...3]modules/react.md
- docs/src/routes/docs/[...3]modules/vue.md
- packages/core/README.md
Updating dev dependency install instructions  for sveltekit and vite per exchange: https://github.com/blocknative/web3-onboard/issues/1645
- [NA] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [NA] Test locally to make sure this feature/fix works
- [NA] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
> update dev dependency install instructions

- packages/react/package.json
- packages/vue/package.json
- yarn.lock
Update the core version within vue and react projects
> Update the core version within vue and react projects

- docs/src/lib/components/FeaturesSection.svelte
- docs/src/lib/components/TestimonialSection.svelte
- docs/src/lib/components/ThemeCustomizer.svelte
- docs/src/lib/components/ThemingSection.svelte
Updating some spelling and web3 onboard references on onboard.blocknative.com 
> Spelling & web3 onboard cohesion update

- docs/package.json
- packages/core/package.json
- packages/core/src/types.ts
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
The documentation/discussion is in the linked issue https://github.com/blocknative/web3-onboard/issues/1632#issuecomment-1521869917 with context. Fixes Typescript error. 
> Fix: i18n type update

- .github/workflows/docs.yml
> Update docs.yml back to 'build' file

- docs/package.json
- docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md
- docs/src/routes/docs/[...1]overview/[...2]contribution-guide/+page.md
- docs/src/routes/docs/[...1]overview/[...3]onboard.js-migration-guide/+page.md
- docs/src/routes/docs/[...2]getting-started/[...1]installation/+page.md
- docs/src/routes/docs/[...3]modules/[...1]core/+page.md
- docs/src/routes/docs/[...3]modules/[...3]react/+page.md
- docs/svelte.config.js
- docs/yarn.lock
> Docs deployment fix (dev)

- packages/core/package.json
- packages/core/src/update-balances.ts
- packages/core/src/views/connect/Index.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Add null check for chain to secondary token balance flow
> Fix: Add null check for chain to secondary token balance flow

- packages/demo/package.json
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
- yarn.lock
Update Walletconnect deps to the latest to expand on customizable options and stability
> Update: Walletconnect deps to the latest to expand on customizable options and stability

- packages/cede-store/package.json
- packages/dcent/package.json
- packages/keepkey/package.json
- packages/keystone/package.json
- packages/react/package.json
- packages/vue/package.json
- packages/walletconnect/package.json
Bump missed versions for publish
> Fix: Bump missed versions for publish

- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Bump versions to fix build/publish of React & Vue packages
> Bump versions to fix build/publish of React & Vue packages

- packages/core/package.json
- packages/core/src/views/account-center/Maximized.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Add null check for primaryWallet connectChain within account center maximized for conditional rendering of protect RPC option. Without this when selecting `Disconnect all wallets` an error is thrown in the console.
> Fix: Add null check for primaryWallet connectChain within account center maximized

- package.json
- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/vue/package.json
Hotfix to add null check to conditional Protect RPC display when disconnecting all wallets from Account Center maximized
> Release 2.23.1 (develop)

- docs/src/routes/docs/[...4]wallets/[...9]injected/+page.md
Update platforms Trust wallet is available on within injected docs
> Fix: Docs - Update platforms Trust wallet is available on within injected docs

- .circleci/config.yml
> Add CI for Venly Module

- docs/src/app.html
Update GA script on docs
[https://www.notion.so/blocknative/Add-GA4-to-Onboard-Subdomain-5d7bde661f604aa1a450ef4d9ce33f9b](https://www.notion.so/blocknative/Add-GA4-to-Onboard-Subdomain-5d7bde661f604aa1a450ef4d9ce33f9b)
- [NA ] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [NA] Add or update relevant information in the documentation
- [NA] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [NA] Add/update the appropriate package README (if applicable)
- [NA] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/ …
> update Google Analytics Script

- docs/src/routes/docs/[...4]wallets/[...24]walletconnect/+page.md
Added optional chains to example. Capitalized the C in WalletConnect (title)
> Add optional chains to example

- packages/demo/package.json
- packages/walletconnect/package.json
Fix - Bump missing wc version from previous merge
> Fix - Bump missing wc version from previous merge

- docs/package.json
- docs/src/lib/services/onboard.js
- docs/src/routes/docs/[...4]wallets/[...24]walletconnect/+page.md
- docs/yarn.lock
- packages/coinbase/package.json
- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/walletconnect/README.md
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
- packages/walletconnect/src/v1.ts
- packages/walletconnect/src/v2.ts
- packages/walletconnect/src/validation.ts
- packages/walletconnect/tsconfig.json
- yarn.lock
Add WC validation for props and add additional prop to handle MetaMask usage through WC
Also add `explore` url to docs to allow connecting MetaMask mobile through WalletConnect
Bump coinbase wallet SDK version for bug fixes
Closes: #1815
> Fix: Add WC validation for props, add prop to handle MetaMask usage through WC, Bump Coinbase sdk version

- packages/demo/package.json
- packages/walletconnect/package.json
- packages/walletconnect/src/index.ts
- packages/walletconnect/src/validation.ts
- yarn.lock
File imports for validation within WC to handle ESM envs
Bump walletConnect deps to the latest
> Fix - File imports for validation within WC to handle ESM envs

- .circleci/config.yml
add steps to build-arcana-auth in config.yml
> Fix: Aracana Config

- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
> Update - Bump WC deps to the latest

- packages/injected/package.json
- packages/injected/src/wallets.ts
fix https://github.com/blocknative/web3-onboard/issues/1894
- [] Confirm this PR passes Circle CI checks
> fix: fix fordefi existence check

- docs/src/routes/examples/[...1]connect-wallet/+page.md
Fix missing comma in connect wallet example docs
Sorry I'm too lazy to add a screenshot, it's just one comma
> Fix missing comma in connect wallet example docs

- README.md
- docs/src/lib/services/onboard.js
- docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md
- docs/src/routes/docs/[...2]getting-started/[...1]installation/+page.md
- docs/src/routes/docs/[...3]modules/[...1]core/+page.md
- docs/src/routes/docs/[...3]modules/[...3]react/+page.md
- docs/src/routes/docs/[...3]modules/[...6]vue/+page.md
- docs/src/routes/docs/[...4]wallets/[...11]injected/+page.md
- examples/with-ledger/pages/index.js
- examples/with-nextjs-13/web3-onboard.ts
- examples/with-vite-react/src/web3-onboard.ts
- examples/with-vuejs-v2/src/components/HelloWorld.vue
- examples/with-vuejs/src/App.vue
- packages/core/README.md
- packages/core/package.json
- packages/core/src/icons/caret-light.ts
- packages/core/src/utils.ts
- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/react/package.json
- packages/vue/package.json
Add Arbitrum Nova native support and update examples and docs around this
Update caret-light used in AccountCenter for the network selector icon, to be visible in all built in themes
> Update - Add Arbitrum Nova native support

- packages/injected/package.json
- packages/injected/src/wallets.ts
This PR updates the SDK to support imToken's `wallet_switchEthereumChain` method, as imToken has introduced support for this method since April 29, 2022. The current version of the SDK includes a flag indicating that imToken does not support `wallet_switchEthereumChain`. However, this flag is no longer accurate and needs to be removed to enable seamless integration with imToken.
Changes Made:
- Removed the 'imToken does not support `wallet_switchEthereumChain`' flag from the SDK codebase.
- Tested the modified SDK with the latest version of imToken to ensure compatibility and verify the successful usage of `wallet_switchEthereumChain`.
By updating the SDK to align with imToken's capabilities, developers using imToken will have access to the full functionality of …
> chore: remove imToken does not support wallet_switchEthereumChain flag

- packages/demo/package.json
- packages/walletconnect/package.json
- packages/walletconnect/src/v2.ts
- yarn.lock
Added `wallet_addEthereumChain` & `wallet_switchEthereumChain` to the default optional methods.
This allows wallets to add additional chains to an existing session & perform smooth chain switching.
> [WalletConnect v2] feat: added `wallet_addEthereumChain` & `wallet_switchEthereumChain`

- packages/demo/package.json
- packages/walletconnect/package.json
> Update - Bump versions for WC

- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
> Update - Revert one WC dep bump

- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
Revert one WalletConnect dep bump
> Update - Revert one WalletConnect dep bump

- .circleci/config.yml
update Node version for Torus Build
> Update node version for torus build

- .circleci/config.yml
> Update: Setup metamask module CI

- .circleci/config.yml
> Update: Add solid.js to CI flow

- .circleci/config.yml
Update: Bump node version for Solid package within CI flow
> Update: Bump node version for Solid package within CI flow

- packages/metamask/package.json
- packages/metamask/src/index.ts
MetaMask handling in node envs
> Update: MetaMask handling in node envs

- docs/package.json
- docs/src/routes/docs/[...4]wallets/[...18]metamask/+page.md
- docs/yarn.lock
- packages/demo/package.json
- packages/metamask/README.md
- packages/metamask/package.json
- yarn.lock
This PR bumps the MetaMask SDK version  and adds a gif of the SDK connect flow to the docs/README
> Update: MetaMask sdk version bump, docs enhancement

- docs/src/lib/services/onboard.js
- packages/demo/src/App.svelte
> Change API Keys for blocknative demo and docs site

- docs/package.json
- docs/yarn.lock
- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
Remove the `@walletconnect/modal` dep from the WalletConnect module on recommendation from the WC team as it was causing issue with communicating to the WC servers'
In ref to #2019
> 2.5.2-alpha.1 WalletConnect : [fix] - Remove unnecessary WC module that was causing issues in usage of module

- packages/demo/package.json
- packages/walletconnect/package.json
- packages/walletconnect/src/walletConnect.ts
- yarn.lock
WalletConnect imports update, bump WC package version, bump WC dep version
> ENH - WalletConnect imports update, bump WC package version, bump WC dep version

- .circleci/config.yml
- yarn.lock
Update node version required for Walletconnect package
> [FIX] - Update node version required for Walletconnect package

- .circleci/config.yml
Bump ledger module node version for build to 16.14.2
> Ledger - [FIX] : Bump ledger module node version for build to 16.14.2

- .circleci/config.yml
Bump ledger module node version for build to 18.0.0 because of WC dep
> Ledger - [FIX] : Bump ledger module node version for build to 18.0.0 because of WC dep

- docs/src/routes/docs/[...4]wallets/[...14]injected/+page.md
- packages/demo/package.json
- packages/injected/README.md
- packages/injected/package.json
- packages/injected/src/types.ts
- packages/injected/src/wallets.ts
> feat: rabby support mobile

- packages/demo/package.json
- packages/demo/src/App.svelte
- packages/walletconnect/package.json
- yarn.lock
> Update: WalletConnet deps to latest

- docs/src/routes/docs/[...4]wallets/[...6]coinbase/+page.md
- packages/coinbase/README.md
- packages/coinbase/package.json
- packages/coinbase/src/index.ts
- packages/demo/package.json
- packages/demo/src/App.svelte
- yarn.lock
- Update coinbase wallet dependencies
- Add new init props to constructor
- Add JS docs notes 
- Update docs
> [UPDATE] - Update coinbase wallet dependencies

- docs/yarn.lock
- packages/demo/package.json
- packages/walletconnect/package.json
- yarn.lock
Update WC versions to fix docs build
> Update WC versions to fix docs build

- docs/package.json
- packages/core/package.json
- packages/demo/package.json
- packages/react/package.json
- packages/solid/package.json
- packages/vue/package.json
Core import of wagmi module version
> Fix - Core import of wagmi module version 

- packages/dcent/package.json
bump dcent package version for release
> bump dcent package version for release

- packages/coinbase/package.json
- packages/coinbase/src/index.ts
- packages/common/package.json
- packages/demo/src/App.svelte
- packages/enkrypt/package.json
- yarn.lock
FIX - Coinbase SDK build - Updates to fix build
> FIX - Coinbase SDK build - Updates to fix build

- docs/src/routes/docs/[...4]wallets/[...19]metamask/+page.md
Updates the link to the metamask sdk docs
> Update metamask sdk link

- docs/src/routes/docs/[...3]modules/[...1]core/+page.md
- docs/src/routes/docs/[...3]modules/[...7]vue/+page.md
- docs/src/routes/docs/[...4]wallets/[...12]gnosis/+page.md
- packages/core/README.md
- packages/gnosis/README.md
- packages/gnosis/package.json
Update docs for gnosis/safe package for building within vue env
> Update docs for gnosis/safe package for building within vue env

- packages/demo/package.json
- packages/metamask/package.json
- yarn.lock
Update the metamask-sdk package to version '0.26.5'
> feat: update '@metamask/sdk' package to version '0.27.0'

- .circleci/config.yml
> Release 2.27.0 - Keplr CI patch

- docs/package.json
- packages/core/package.json
- packages/core/src/provider.ts
- packages/core/src/views/chain/SwitchChain.svelte
- packages/demo/package.json
- packages/react/package.json
- packages/solid/package.json
- packages/vue/package.json
There were missing imports and a null fallback that was missing to properly handle adding a new chain
> [FIX]: Core - switch chain when chain isnt available in wallet already

- README.md
updated readme added support keplr wallet
> docs: updated readme 'add support keplr wallet'

- packages/metamask/package.json
- packages/metamask/yarn.lock
Update MetaMask sdk to 0.32.0 
> chore: bump metamask to 0.32.0

- package.json
- packages/coinbase/package.json
- packages/core/package.json
- packages/keystone/package.json
- packages/metamask/package.json
- packages/react/package.json
- packages/solid/package.json
- packages/vue/package.json
- yarn.lock
> keystone package v2.3.11

- .circleci/config.yml
> update node version in CI

- .circleci/config.yml
> bump node version for keystone ci job

- .circleci/config.yml
> Update node version CI for keystone job
