src/views/WalletSelect.svelte
This PR moves the `WalletSelect` component modal logic into an else statement to handle when a wallet isn't auto selected correctly.
closes #8
=> Fix `selectWallet` bug when using auto select functionality

src/interfaces.ts, src/modules/select/wallets/wallet-connect.ts, src/onboard.ts, src/stores.ts, src/views/WalletCheck.svelte, src/views/WalletSelect.svelte
This PR:
- Adds a `walletReset` function to the Onboard.js API. When called it will set all of the internal wallet state to the initial values when Onboard is initialized.
- Updates the WalletConnect module so that it correctly disconnects when either the user closes the session or if the `walletReset` function is called.
- Ensures that all state subscription callbacks are only called when the value changes and only once per change.
=> Feature: Wallet Reset Function

src/interfaces.ts, src/modules/select/wallets/authereum.ts, src/validation.ts
I've had some feedback wanting Authereum notifications when using Onboard. I've added an optional initialisation value to set this behaviour by copying those for Torus.
Note: This PR switches the default to allowing notifications. If you don't want this I can add a little logic to swap this.
=> Made disabling Authereum notifications optional

src/modules/select/wallets/metamask.ts
Currently Metamask Mobile is detected but can't be used due to it not being made available in the wallet select menu.
I've set the mobile flag to true so that it will appear.
=> Add Metamask mobile support

src/components/Wallets.svelte
I had trouble replicating the behavior in #199 but have seen it happen before. I believe that adding a key to the `each` iteration should help with rendering the list of wallets and removing the fade in transition should help reduce complexity.
=> Add key to wallet buttons

src/modules/select/wallets/portis.ts, src/modules/select/wallets/squarelink.ts, src/utilities.ts
Having the jsonrpc version string is mandatory according to https://www.jsonrpc.org/specification.
Depending on the node the missing version string is problematic. Having Metamask connected to a local parity node resulted in onboard.js not detecting the network version. Also on the browser console you would see an error logged from Metamask:
```
code: -32600
message: "Unsupported JSON-RPC protocol version"
```
With this patch applied no error is logged in the console and the connection to the local Parity node is accepted.
=> fix: add "jsonrpc: '2.0'" to sendAsync methods

src/onboard.ts, src/stores.ts
This PR makes changes to so that the `wallet` subscription is called if a wallet disconnects.
=> Fix: Wallet Subscription

src/modules/select/wallets/hd-wallet.ts, yarn.lock
The update to the `ethereumjs-util` dependency required a change to how the `toChecksumAddress` was called which was missed in the original PR #407 due to browser caching during local testing.
=> Fix: HD wallet

src/components/Modal.svelte
As described in #412, if the font is missing, the default font is rendered, which looks pretty bad. 
I took the fallbacks from https://www.cssfontstack.com/Helvetica.
=> Add fallback fonts

src/modules/select/wallets/opera-touch.ts
Opera Touch now throws errors if a rpc request is made before the enabled permissions have been granted. This PR ensures that no rpc calls are made before the user has enabled access.
=> Fix: Ensure wallet enabled before making rpc requests

src/modules/select/wallets/providerEngine.ts
This PR handles and logs any errors that are thrown by the `web3-provider-engine`. This will hopefully fix #435 until we can move to a different provider implementation. The problem seemed to be that when the provider-engine threw an error, for some reason the dynamic import would fail, so it would try importing the js chunk again which would instantiate another provider connection, thus instantiating another block poll. This would get it stuck in a loop of errors.
=> Handle and log provider engine error

src/modules/check/accounts.ts, src/views/Onboard.svelte, src/views/WalletCheck.svelte
This PR removes hard coded padding styles from the account select element to make it easily customizable.
=> Remove hard coded style on account select

src/modules/check/accounts.ts
- Add missing quotation in html string which was causing account select dropdown to render incorrectly
Fixes #454
=> Add missing quotation

src/modules/select/wallets/torus.ts
Reverts blocknative/onboard#462 since we are locking Torus to previous version.
=> Revert "Issues/torus type error"

package.json, yarn.lock
This commit updates GridPlus-related modules to prepare for what will be
breaking changes in firmware. The updated packages are themselves backwards
compatible so current users will see no difference in functionality.
=> Updates GridPlus connector in anticipation of upcoming Lattice firmware release

rollup.config.js
The Lattice connector imports `eth-lattice-keyring` and uses it to build requests.
I noticed it was not included in this repo's rollup config and including it changes the`dist/cjs/lattice-xxxxxxxx.js` build:
```
_context11.next = 20;
return new Promise(function (resolve) {
resolve(_interopNamespace(require('eth-lattice-keyring')));
});
```
Previously, it was:
```
_context11.next = 20;
return new Promise(function (resolve) {
resolve(require('./index-b08a3c95.js'));
});
```
I'm assuming `eth-lattice-keyring` should be included here and I believe this is related to the following issue in our Yearn integration: https://github.com/iearn-finance/yearn-finance/issues/73, but this is not really my area of expertise so feedback here is welcome!
**UPDATE:** I tested these changes with a local copy …
=> Adds eth-lattice-keyring to rollup config

package.json, src/services.ts
- Passes Onboard version to the SDK so that it can be sent to the server
Note: Tests currently fail due to the latest SDK not yet being used that accepts this parameter. I will increment the SDK version once it is released, but would like to do a final test on our staging environment first.
=> 1.18.0-0.3.0: Enhancement - Send Onboard version

package.json, yarn.lock
- Updates to version `3.1.0` of the Blocknative SDK
=> 1.18.0-0.3.1: Update SDK

package.json, src/interfaces.ts, src/modules/select/index.ts, src/modules/select/wallets/metamask.ts
- Fixes TypeScript interface bug that was enforcing `isMobile` parameter as required for all wallet init objects.
Fixes #519
=> 1.21.0-0.0.1: [fix] - isMobile Parameter

package.json, src/onboard.ts, src/services.ts
Upon re-initialization of Onboard:
- Closes WebSocket connection if it exists
- Resets wallet state back to initial state
Closes #603
=> 1.29.0-0.1.0: [enhancement] - Cleanup Upon Re-Initialization

package.json, pull_request_template.md, rollup.config.js, src/@types/index.d.ts, src/interfaces.ts, src/onboard.ts, src/utilities.ts, src/validation.ts, yarn.lock
Adds support for ens.
```js
import Onboard from 'bnc-onboard'
import Web3 from 'web3'
let web3;
const onboard = Onboard({
dappId: apiKey,       // [String] The API key created by step one above
networkId: networkId  // [Integer] The Ethereum network ID your Dapp uses.
subscriptions: {
wallet: wallet => {
web3 = new Web3(wallet.provider)
},
ens: ens => {
console.log(ens)
// { name: String, getText: Function, content: String }
}
}
});
```
=> 1.29.0-0.5.3: [feature] Adds ens support

package.json, src/modules/select/wallets/keepkey/index.ts
This PR fixes an issue that occurs when attempting to sign an Ethereum transaction with an `undefined` transaction value using a KeepKey wallet.
This issue happens because when `value` is `undefined` for a transaction (e.g. when interacting with a non-payable smart contract method), an empty string value is passed to the [@shapeshiftoss/hdwallet-keepkey](https://github.com/shapeshift/hdwallet/tree/master/packages/hdwallet-keepkey) `ethSignTx`, which expects a string in hex format prefixed with `0x`, as expressed in the [`ETHSignTx` interface](https://github.com/shapeshift/hdwallet/blob/c9baf29278bb13478f91c9a9d42abd588b468d65/packages/hdwallet-core/src/ethereum.ts#L43-L44) and demonstrated in the [integration tests](https://github.com/shapeshift/hdwallet/blob/master/integration/src/ethereu …
=> 1.29.0-0.5.6: [fix] keepkey eth sign transaction issue

package.json, src/interfaces.ts, src/utilities.ts
Adds `avatar` to the ens object on the ens subscription:
```js
ens: (ens) => {
console.log(ens.avatar) // https://avatarurl.io
}
```
=> 1.29.0-0.5.7: Adds avatar to ens object

package.json, src/modules/select/wallets/keepkey/index.ts
`HookedWalletSubprovider`'s `signMessage` and `signPersonalMessage` expect `0x`-prefixed hex strings, while `hdwallet-keepkey` expects a UTF-8 string.
=> 1.29.0-0.5.8: [fix] keepkey message signing

package.json, src/modules/check/network.ts
Onboard will try and execute the `wallet_switchEthereumChain` RPC request to switch networks for the user, if the RPC request isn't implemented by the wallet's provider it will fallback to displaying the Switch Network modal.
=> 1.32.0-0.1.0: Switch network if RPC request is available

package.json, src/interfaces.ts, src/modules/select/index.ts, src/validation.ts
Adds the ability to specify which wallets to show for mobile or desktop views.
```js
{
walletName: 'metamask'
// Only displays Metamask Wallet on desktop
display: { mobile: false }
}
```
Addresses #605
=> 1.33.0-0.1.1: [feature] Adds display options for wallets

package.json, src/modules/select/wallets/fortmatic.ts
Allows adding an `rpcUrl` to the Formatic wallet init option in order to use Formatic with custom chains such as Matic or Skale. See [Formatic docs](https://docs.fortmatic.com/web3-integration/network-configuration#switch-network-to-custom-node) for details.
Address #643
=> 1.33.0-0.2.1: [feature] Adds optional custom rpc url for formatic

package.json, src/utilities.ts
Reduce client side bundle size by dynamically importing the ENS library only if the developer wants to utilize that feature.
Partially addresses #650.
=> 1.33.0-0.3.3: [refactor] Lazy load ens

package.json, src/modules/check/network.ts
Fixes bug where multiple Metamask switch network prompts were shown after user canceled the request.
Fixes #672
=> 1.34.1-0.1.0: [fix] network switch bug

package.json
This includes fixes for a few patches which is not urgent as the 1.6.0 upgrade but useful to include on onboard.js for developers as part of the next release cycle
**1.6.1**
- upgrade ws version
- fix mobile link filtering
- fix mobile link state update
- fix react-native connector prototype
**1.6.2**
- add direct link when a single desktop link is available
- fix re-subscription on WebSocket error
- fix deep link triggered on unsafeSend method
=> 1.34.1-0.1.1: [update] WalletConnect v1.6.2

package.json, src/interfaces.ts, src/stores.ts
=> 1.34.2-0.0.3: Refactor the balance syncer to not start polling

package.json, yarn.lock
Update walletlink to 2.1.11 to fix regression where chainChanged event was not getting emitted in prior release
=> 1.34.2-0.0.4: [update] walletlink to 2.1.11

package.json, src/modules/select/wallets/binance-chain-wallet.ts, src/stores.ts
* Reverts the original fix to the polling issue
* Implements a fix isolated to BSC wallet module
* Fix now won't allow call to get balance until an address is defined
=> 1.34.2-0.0.6: [fix] BSC wallet balance polling

package.json, yarn.lock
- Previous commit reverted keystone dep to 0.7.7
- This commit reverts the yarn.lock version for keystone deps causing errors
=> 1.34.2-0.0.10: [fix] Revert yarn.lock versions

package.json, src/modules/select/wallets/wallet-connect.ts
WalletConnect wasn't getting passed the chainId causing it to default to 1.
Fixes #699 & #471
=> 1.35.0-0.0.4: [fix] Add chainId to WalletConnect constructor

package.json, rollup.config.js, src/@types/index.d.ts, src/modules/select/index.ts, src/modules/select/wallets/mewwallet.ts, yarn.lock
Temporarily removes (comments out) MEW wallet due to problems with installing deps on M1 macs. Once [this issue](https://github.com/MyEtherWallet/MEWconnect-web-client/issues/75) is fixed we can add back in.
=> 1.35.1-0.0.2: [fix] - Temporarily Remove MEW wallet

package.json, src/modules/select/index.ts
The generic provider is injected always when Metamask is added in the custom wallet list and also detected by onboard.js
I used the same approach that is already in the `if/else if` for the `defaultWalletNames` so they are using a similar code style
https://github.com/blocknative/onboard/blob/4751b5e3fad237b6933b8f2f356a8c0f201b4510/src/modules/select/index.ts#L124-L129
=> Generic provider is injected always when using a custom list

package.json, src/utilities.ts
=> 1.35.4-0.0.2: [chore] Add Fantom networks

package.json, src/modules/select/wallets/xdefi.ts
Fix to allow onboardJS to connect to XDeFi Wallet if clicked on the 'XDeFi Wallet' option, as currently it recognizes it as MM and doesn't allow the user to connect to it.
Tested it on the onboardJS react-demo-app
=> 1.36.0-0.1.1: [fix] remove providerName check for XDeFi Wallet

package.json, yarn.lock
Updates walletlink to a version of the protocol that supports returning a 4092 error code for `switchEthereumChain` requests where the network is not recognized by the wallet. This enables dapps to send an `addEthereumChain` request after receiving the 4092 error code.
=> 1.37.0-0.0.1 : [Update] - Walletlink version to 2.4.2

package.json, yarn.lock
Update yarn.lock deps to run in Node v12 container
- [ x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ x] The box that allows repo maintainers to update this PR is checked
- [ x] I tested locally to make sure this feature/fix works
- [ x] This PR passes the Circle CI checks
=> 1.37.0-0.0.2 : [fix] - Update yarn.lock deps to run in Node v12 container

package.json, pull_request_template.md
Update PR checklist for PRs merging forks
- [ x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x ] The box that allows repo maintainers to update this PR is checked
- [ x] I tested locally to make sure this feature/fix works
- [x ] This PR passes the Circle CI checks
=> 1.37.0-0.0.3 : [enhancement] - Update to PR checklist for fork merges to run yarn with nove v12

package.json, src/modules/select/wallets/coinbase.ts
Update coinbase injected wallet to use `window.ethereum` provider if available.
=> [coinbase wallet] use window.ethereum provider if available

packages/core/README.md, packages/keepkey/package.json, packages/trezor/package.json
- More notes in Readme around Create React App usage with webpack  
- Trezor connect package update
- Enforcement of Node >=v16 for Keepkey module
=> More notes in Readme and  trezor connect package update

package.json, yarn.lock
Updating walletlink to the latest minor version which has a fix for returning an error if the dapp requests changing to a chainId the wallet is already on https://github.com/walletlink/coinbase-wallet-sdk/pull/294
=> fix: Update walletlink to 2.4.6

package.json, src/modules/select/wallets/detectedwallet.ts
This should fix errors when doing walletSelect in browsers without provider (window.ethereum or window.web3)
=> fix: wallet select error when no provider

package.json, yarn.lock
Update walletlink to 2.5.0 to add [wallet_watchAsset support](https://github.com/coinbase/coinbase-wallet-sdk/pull/336)
=> 1.38.1-0.0.1 : [update] - walletlink version to 2.5.0

packages/walletlink/package.json
Update walletlink to 2.5.0 to add https://github.com/coinbase/coinbase-wallet-sdk/pull/336
=> Update V2 - Update walletlink version to 2.5.0

package.json, src/modules/select/index.ts
Logic needed to be updated to check that the provider exists rather than if the name of the provider exists. That defeated the purpose of a "detected wallet".
Fixes #765
=> 1.38.1-0.0.3: [fix] Detected wallet logic

package.json, src/modules/select/wallets/1inch.ts, src/utilities.ts
There was an issue with how the 1inch wallet connected to the injected provider. This has been resolved
=> 1.38.1-0.0.4 : [fix] - 1inch wallet

packages/react/src/index.ts
Add disconnect method to react package that takes a `wallet<WalletState>` as a param
=> Feature - Add disconnect method to react package

packages/injected/package.json, packages/injected/src/index.ts
Added provider check that was breaking opera browser
=> Added provider check that was breaking opera browser

packages/walletconnect/package.json, packages/walletconnect/src/index.ts
- Adds a static JSON RPC providers mapping for all requests that need to go to an RPC endpoint
Fixes #856
=> walletconnect-v2.0.1: [fix] - Add RPC Providers

packages/react/package.json
Update core version for react components 2.0.3 -> 2.0.6
=> Update core version for react components

.circleci/config.yml, package.json, packages/common/package.json, packages/common/src/types.ts, packages/core/package.json, packages/core/src/index.ts, packages/demo/package.json, packages/fortmatic/package.json, packages/gnosis/package.json, packages/injected/package.json, packages/keepkey/package.json, packages/keystone/package.json, packages/ledger/package.json, packages/mew/package.json, packages/portis/package.json, packages/react/package.json, packages/torus/package.json, packages/trezor/package.json, packages/walletconnect/package.json, packages/walletconnect/src/index.ts, packages/walletlink/package.json
**[core:v2.0.7]**
- Export EIP1193 type directly from package
- Update `common` package
**[common:v2.0.2]**
- Add generic request type to EIP1193Provider for ethers External Provider compatibility
**[all-packages]**
- Add `type-check` script and add to CI process
=> [fix] - Provider Types

packages/core/README.md, packages/core/package.json, packages/core/src/connect.ts, packages/core/src/streams.ts, packages/core/src/types.ts, packages/core/src/validation.ts, packages/core/src/views/connect/ConnectedWallet.svelte, packages/core/src/views/connect/ConnectingWallet.svelte, packages/core/src/views/connect/Index.svelte, packages/core/src/views/connect/SelectingWallet.svelte
- Lifts all logic out of sub modal components in to the main index for the connect flow
- Modifies type and validation to allow for an options object for the `autoselect` parameter so that modals can be disabled when auto selecting a wallet:
```javascript
const previouslySelectedWallet = window.localStorage.getItem('selectedWalletLabel')
onboard.connectWallet({
autoSelect: {
label: previouslyConnectedWallet,
disableModals: true
}
})
```
The original way of calling connect wallet with the `autoselect` parameter as a string is also still valid and will get converted to the new options object internally.
Closes #849
=> web3-onboard/core:v2.0.9: [enhancement] - Autoselect Disable Modals

packages/injected/package.json, packages/injected/src/types.ts, packages/injected/src/validation.ts
- Fixes incorrect validation for the `filters` property for injected wallets so that it accepts a boolean or and array of strings.
=> web3-onboard:v2.0.2: [fix] - Injected Filters

packages/react/package.json, packages/react/src/index.ts
This sets initial react state in the hooks, instead of defaulting to null.
Right now, if a hook is used in a component that renders after you connect your wallet, it won't have any wallets in it's react state. Unless a wallet change happens afterwards that triggers the subscription to update it. Initially, it's all null.
This problem applies to all 3 react hooks.
=> fix missing initial states in react hooks

packages/common/package.json, packages/common/src/types.ts, packages/keepkey/package.json, packages/keepkey/src/index.ts, packages/keystone/package.json, packages/keystone/src/index.ts, packages/keystone/tsconfig.json, packages/ledger/package.json, packages/ledger/src/index.ts, packages/trezor/package.json, packages/trezor/src/index.ts
- Adds `request` function to provider, so that all unpatched RPC methods will get forwarded on to the connected RPC endpoint
- Patches `eth_sendTransaction` RPC method to sign transaction and then send the raw transaction to the RPC endpoint
=> [fix]: Hardware Wallet Providers Send Transaction

packages/core/package.json, packages/core/rollup.config.js, yarn.lock
This PR copies `src/i18n/en.json` to the dist directory to avoid breaking types during a build with vite.
fixes: #913
=> fix: exports i18n/en.json to dist

packages/core/src/index.ts, packages/core/src/utils.ts
- Moves device detection logic in to a function that is only called once it is known that the window object is available which fixes a bug in SSR environments.
Fixes #930
=> [fix] - Window Not Available

packages/core/src/views/account-center/WalletRow.svelte
This PR fixes a UI bug where some text was showing in the wallet row menu that shouldn't be due to lacking a z-index.
=> [fix]: Add z-index to wallet row menu

packages/core/package.json, packages/core/src/views/connect/Index.svelte
Add check for connection rejection when autoSelecting Wallet to close out [928](https://github.com/blocknative/web3-onboard/issues/928)
=> [core-v2.2.1] : Fix - Add check for connection rejection when autoSelecting Wallet

packages/react/package.json
=> [react-v2.1.1] - Updates core version

packages/core/package.json, packages/core/src/views/account-center/Minimized.svelte
Adds a check causing this error to be thrown when diconnecting a wallet
=> [core-v2.2.2] : Fix - Error arising after disconnecting wallet

packages/react/package.json, packages/react/src/index.ts
As discussed at https://github.com/blocknative/web3-onboard/issues/923, this PR covers a missing feature where the `react` package was not exposing if `setChain` had success.
=> [react] feat: return setChain success

packages/core/src/icons/caret-light.ts, packages/core/src/icons/caret.ts, packages/core/src/views/account-center/Maximized.svelte, packages/core/src/views/account-center/Minimized.svelte, packages/core/src/views/shared/NetworkSelector.svelte
Prior to this change the chevron(caret) icons were not selectable and did not open the network drop-down. 
With this change the icons are passed from the parent element and therefore can be custom to the component.
The icon is then used as a background image within the select giving a more understandable UX
For this to work the line breaks needed to be removed form the caret icons and min-width for select increased.
=> [core] : Enhancement - Dropdown select icon opens options

package.json, src/modules/select/wallets/keystone.ts, src/modules/select/wallets/trezor.ts
Update trezor module to not validate path using old method
=> 1.38.2-0.0.1 : [fix] - Update trezor module to not validate path using old method

packages/core/package.json, packages/core/src/views/shared/Modal.svelte, packages/demo/package.json, packages/react/package.json
Add methods to prevent scrolling of background when modal is open - Handles issue #973
=> [core-v2.2.7, react-v2.1.6] : fix - Add methods to prevent scrolling of background when modal is open

.circleci/config.yml, packages/coinbase/package.json, packages/common/package.json, packages/core/package.json, packages/core/src/views/account-center/Minimized.svelte, packages/fortmatic/package.json, packages/gnosis/package.json, packages/injected/package.json, packages/keepkey/package.json, packages/keystone/package.json, packages/ledger/package.json, packages/magic/package.json, packages/mew/package.json, packages/portis/package.json, packages/react/package.json, packages/torus/package.json, packages/trezor/package.json, packages/walletconnect/package.json
Update internal deps and add check for alpha flag on release branch, break if found
=> CI Develop Flow Fix - Update internal deps, add check for alpha flag on release branch

README.md, packages/vue/README.md, packages/vue/package.json, packages/vue/src/index.ts, packages/vue/src/types.ts, packages/vue/tsconfig.json, yarn.lock
Continuation of https://github.com/blocknative/web3-onboard/pull/911
=> Feature: Add vue package

packages/coinbase/package.json, packages/coinbase/src/index.ts, packages/core/package.json, packages/core/src/store/actions.ts, packages/core/src/utils.ts, packages/injected/src/types.ts, packages/react/package.json
This PR includes changes to includes
-  `Wallet` in the Coinbase package wallet label - Per Coinbase team request
-  Dedup functionality on wallet label so there won't be two `Coinbase Wallet`s visible
=> [coinbase, core, react] : Update - Coinbase wallet name and dedupe on wallet label

packages/common/package.json, packages/common/src/elements/TableHeader.svelte, packages/common/src/views/AccountSelect.svelte, packages/core/package.json
Empty addresses will now be shown by default.
=> Show empty addresses by default

packages/core/README.md, packages/core/package.json, packages/core/src/views/account-center/Maximized.svelte, packages/core/src/views/account-center/Minimized.svelte, packages/core/src/views/connect/ActionRequired.svelte, packages/react/package.json
- Add background styling variable to the Action Required modal `--onboard-action-required-modal-background` with fallbacks closing #1013 
- Remove unused styling classes causing warning in build
=> [core] : feature - Add background styling variable to the Action Required modal

package.json, src/modules/select/wallets/opera.ts
- Switches Opera detection to using the provider flag now that it is consistent across environments
- Updates CI for new branch naming
Closes #908
=> 1.38.3: [fix] - Opera Provider Detection

.circleci/config.yml, packages/dcent/src/index.ts, packages/injected/package.json
- Added CI for DCent package
- Remove unneeded code and logs
- Formatted file
- Incremented version for injected wallets for removal of DCent injected
=> [dcent - v1.0.0-alpha.1, injected v2.0.8-alpha.1] : Update - CI and cleanup

packages/keystone/package.json, packages/keystone/src/index.ts
Use let assignment for AirGappedKeyring as its currently using const and then reassigning variable
=> fix(keystone): use let for AirGappedKeyring const

packages/dcent/package.json, packages/dcent/src/icon.ts, packages/injected/package.json, packages/injected/src/icons/dcent.ts, yarn.lock
- Modifies the var and classnames in the dcent icons to remove clashes with other icons
=> [injected][dcent] - Fixes clashing svg vars

packages/walletconnect/package.json, packages/walletconnect/src/index.ts
Per comments on [this PR](https://github.com/blocknative/web3-onboard/pull/1019) there was an issue where, depending on the build tool, `QRCodeModal` would be either nested under default like: `{ default: QRCodeModal }` and other times would be top level when imported. This PR essentially makes it so that it will work in both scenarios. 
**Below you will find some research behind why this may be the case:**
I looked at these two import statements and noticed something.
https://github.com/blocknative/web3-onboard/blob/faee8bd865e7b090b8b6e4df09649d296a3bca23/packages/walletconnect/src/index.ts#L28-L32
Both imports are `default` imports but while `WalletConnect` is defined `QRCodeModal` is undefined.
What I determined is that `@walletconnect/client` has an esm build while …
=> Fixes walletconnect import issues for some build tools

packages/common/package.json, packages/common/src/types.ts, packages/core/README.md, packages/core/package.json, packages/core/src/provider.ts, packages/core/src/validation.ts, packages/react/package.json
Resolves #1020 and #948.
As outlined in #1020, it's sometimes necessary to pass a custom (typically public) RPC when adding a new chain to the user's wallet.
=> Feature: optional public RPC and block explorer Chain params

packages/core/package.json, packages/react/package.json, packages/web3auth/package.json
Bump package versions for core, react and web3auth
=> [core-v2.2.13-alpha.2 , react-v2.1.10-alpha.2, web3auth-v2.0.1-alpha.1 ]: fix -  package bump

packages/core/src/views/notify/Notification.svelte, packages/core/src/views/notify/StatusIconBadge.svelte
Forgot to run `yarn type-check` locally before merging
Update types causing build to break
=> [core-v2.3.0-alpha.1] : Fix - Update types causing build to break

packages/core/README.md, packages/core/package.json, packages/core/src/views/notify/NotificationContent.svelte, packages/react/package.json, packages/vue/package.json
Update - Line height and documentation for notifications
The line height needs to be equal to the font size to be able to handle letters with tails below the line or they will be cut off
=> [core-v2.3.0-alpha.3, react-v2.2.0-alpha.4, vue-v2.1.0-alpha.3] : Update - Line height and documentation

packages/core/package.json, packages/core/src/index.ts
Fixes #1105, a `typeof` check which was evaluating to `true` even when `notify` would be `undefined`.
=> Fix typeof check for notify in core

packages/coinbase/package.json, packages/common/package.json, packages/core/package.json, packages/dcent/package.json, packages/demo/package.json, packages/fortmatic/package.json, packages/gnosis/package.json, packages/injected/package.json, packages/keepkey/package.json, packages/keystone/package.json, packages/ledger/package.json, packages/magic/package.json, packages/mew/package.json, packages/portis/package.json, packages/react/package.json, packages/torus/package.json, packages/trezor/package.json, packages/vue/package.json, packages/walletconnect/package.json, packages/walletlink/package.json, packages/web3auth/package.json
We want our repo listed here:
Adding this field allows npm to auto add it to the package page.
=> Adds repository field

packages/react/package.json, packages/react/src/index.ts
Provides missing getServerSnapshot and fixes issue #1097.
=> [react-v2.2.2-alpha.3]: Fix - Next.js SSR support

package.json, packages/injected/package.json, packages/injected/src/wallets.ts
For some strange reason, the liquality wallet was being constrained to the arbitrum namespace. As a result, web3 onboard is not able to connect to liquality except for arbitrum.
Liquality supports regular `window.ethereum` with EIP1993.
This PR fixes this by using `window.ethereum` as injection namespace
=> [injected-v2.0.13-alpha.1] : fix - Liquality wallet injection update

packages/core/package.json, packages/core/src/validation.ts, packages/react/package.json, packages/vue/package.json
This fixes the validation for the object that is passed to the `connectWallet` function so that it does not accept and empty object which causes errors.
=> [core: 2.4.0-alpha.2] : [fix] - Autoselect Validation

.circleci/config.yml
Previous node version defined for Docker Image is unavailable, bumping to 12.13.1
=> [1.38.4] : Fix CI with Node version bump

packages/core/package.json, packages/core/src/notify.ts, packages/core/src/updateBalances.ts, packages/react/package.json, packages/vue/package.json
This PR adds functionality to update Balances of connected wallets who might be the sender(`transaction.to`) or receiver(`transaction.from`) or both if both are connected to onboard. This only occurs on delivery of a notification with a type of `success`.
Also added is functionality to coerce the case to lower of the compared addresses in the `updateBalance` function
=> [core-v2.4.0-alpha.5, react-v2.2.3-alpha.3, vue v2.1.3-alpha.3] : Feature - Update balances on success notification

packages/core/README.md, packages/core/package.json, packages/core/src/views/shared/Modal.svelte, packages/demo/package.json, packages/react/package.json, packages/vue/package.json
Adds `--onboard-modal-color` (to compliment `--onboard-modal-background`).
Maintains the current default color `initial` (via `all: initial` on `<onboard-v2/>`)
Needed to change default text color for modals such as:
=> [core-v2.4.0-alpha.8] : Enhancement - Add --onboard-modal-color

packages/core/README.md, packages/core/package.json, packages/core/src/validation.ts, packages/core/src/views/account-center/Maximized.svelte, packages/core/src/views/account-center/Minimized.svelte, packages/core/src/views/account-center/WalletRow.svelte, packages/core/src/views/shared/NetworkSelector.svelte, packages/react/package.json, packages/vue/package.json, pull_request_template.md, yarn.lock
Exposed variables for Alien World per [discord](https://discord.com/channels/542403978693050389/989280576924164126/994573545357181028)
```
--account-center-minimized-background
--account-center-maximized-upper-background
--account-center-maximized-network-section
--account-center-maximized-app-info-section
--account-center-minimized-address-color
--account-center-maximized-address-color
--account-center-maximized-account-section-background-hover
--account-center-maximized-action-background-hover
--account-center-minimized-chain-select-background
--account-center-network-selector-color
--account-center-maximized-network-selector-color
--account-center-minimized-network-selector-color
--account-center-app-btn-text-color
--account-center-app-btn-background …
```
=> [core-v2.4.0-alpha.9, react-v2.2.3-alpha.5, vue-v2.1.3-alpha.6] : Feature - Expose css variables per AlienWorld and version bumps

packages/core/src/i18n/en.json
=> notify copy updates

packages/coinbase/package.json, packages/common/package.json, packages/common/src/elements/TableHeader.svelte, packages/common/src/views/AccountSelect.svelte, packages/core/package.json, packages/dcent/package.json, packages/fortmatic/package.json, packages/gnosis/package.json, packages/injected/package.json, packages/keepkey/package.json, packages/keepkey/src/index.ts, packages/keystone/package.json, packages/ledger/package.json, packages/magic/package.json, packages/mew/package.json, packages/portis/package.json, packages/react/package.json, packages/torus/package.json, packages/trezor/package.json, packages/vue/package.json, packages/walletconnect/package.json, packages/walletlink/package.json, packages/web3auth/package.json
This PR includes:
- Style modifications to the rendered error message in the account select modal for hardware wallets
- Modifies the keepkey pin entry error to render a string message
- Formats the error returned from rpc for when the network cannot be detected
Closes #982
=> [common:2.1.6-alpha.1] [keepkey:2.1.6-alpha.1] - Better Error Messages

packages/core/package.json, packages/core/src/views/connect/Index.svelte, packages/react/package.json, packages/vue/package.json
This PR fixes an issue where the call to `connectWallet` would not resolve or reject if called with the `autoSelect` parameter for a wallet that is no longer available.
Fixes #1153
=> [core: 2.6.0-alpha.2] - [fix] - Autoselect  with disabled modals resolve

packages/trezor/package.json, packages/trezor/src/index.ts
This PR resolves an issue were we pass a nonce missing 0x prefix. 
To get the transaction signed on line 404 in [trezor/src/index.ts](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/trezor/src/index.ts#L395) we call `Transaction.fromTxData`. The `Transaction` class is coming from `@ethereumjs/tx`.
When calling `fromTxData` that package will instantiate a class extending their `BaseTransaction`. The `BaseTransaction` constructor will try to convert the `nonce` to first a `buffer` and then `BigInt` [see here](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/baseTransaction.ts#L101)  . To convert the string to a buffer they rely on `toBuffer` from `@ethereumjs/util`, this method will throw if passed a string not prefixed with …
=> Fix trezor nonce

packages/keystone/package.json
Without this line, some build systems fail to import the module.
=> Fix: add "main" to Keystone's package.json

packages/demo/package.json, packages/demo/src/App.svelte, packages/injected/package.json, packages/injected/src/wallets.ts, yarn.lock
- Updated Binance Wallet provider patch as their current injected provider is now READONLY which was causing issues with adding event listeners and properties to the `window.BinanceChain` object
- Removed unnecessary patches with current provider
- Also updated some typing to remove warnings for `parseInt` params
Fixes #1169 @ReflectiveChimp
=> [injected-v2.0.15-alpha.2] : Fix - Updated Binance Wallet provider patch

packages/core/package.json, packages/gas/package.json, packages/gas/src/get.ts, packages/gas/src/stream.ts
After working with the Gas API for an upcoming feature, I realised that it is more convenient if the responses came back as an array of responses rather than a mapping of chainId -> response. This PR modifies the API to do that and increments versions.
=> [gas:2.0.0-alpha.2] [core:2.6.0-alpha.7] - [enhancement] - Modify Gas API Response

packages/common/package.json, packages/common/rollup.config.js, packages/core/package.json, packages/core/rollup.config.js, packages/demo/package.json, packages/injected/package.json
Downgrades terser minify es version to 2017
Recommended by @Adamj1232 Since the rest of the projects has a JS operator cut off at ES 8 (2017) and the current was causing issues for Beefy
=> common-v2.1.7-alpha.5, core-v2.6.0-alpha.8......]:Fix: bundler-minify-version

packages/common/package.json, packages/common/src/elements/AddressTable.svelte, packages/common/src/types.ts, packages/common/src/utils.ts, packages/common/src/validation.ts, packages/common/src/views/AccountSelect.svelte, packages/core/package.json, packages/core/src/provider.ts, packages/core/src/views/connect/Index.svelte, packages/demo/package.json, packages/react/package.json
This PR: 
- enforces the weiToETH function to accept only strings from core and common 
- returns ethers.BigNumber for GetInterfaceHelpers used by Ledger
=> [common-v2.1.7-alpha.5, core-v2.6.0-alpha.8, react-v2.2.5-alpha.7]fix: weifix

packages/coinbase/package.json, packages/common/package.json, packages/common/rollup.config.js, packages/core/package.json, packages/core/rollup.config.js, packages/dcent/package.json, packages/demo/package.json, packages/fortmatic/package.json, packages/gnosis/package.json, packages/injected/package.json, packages/keepkey/package.json, packages/keystone/package.json, packages/ledger/package.json, packages/magic/package.json, packages/mew/package.json, packages/portis/package.json, packages/react/package.json, packages/torus/package.json, packages/trezor/package.json, packages/vue/package.json, packages/walletconnect/package.json, packages/walletlink/package.json, packages/web3auth/package.json, yarn.lock
This PR is to remove Terser (the rollup package that minifies) from Common and Core packages.
This changes requires bumping all packages that use/import Common or Core packages
=> [common-v2.1.8-alpha.1, core-v2.7.0-alpha.3, react-v2.2.6-alpha.2, vue-v2.1.6-alpha.2...]: Fix - Remove Terser from Rollup(minification)

packages/core/package.json, packages/core/src/views/Index.svelte, packages/react/package.json, packages/vue/package.json
This PR dynamically imports both the Account Center and Notify code. For apps that have these features disabled, this will save ~35kb of user bandwidth on the initial JS download.
=> [core:2.7.0-alpha.4] - Dynamically import Notify and Account Center

packages/core/README.md, packages/react/README.md, packages/vue/README.md
Update docs to reflect the non-bias RPC provider ability through showing both Alchemy and Infura are acceptable RPC providers to pass to W3O
Closes PR #1161
=> Update docs to reflect the non-bias RPC provider ability

packages/react/README.md, packages/react/package.json, packages/react/src/hooks/useConnectWallet.ts
Add WalletState[] return value to `connect` and `disconnect` hooks within the React Package.
This allows for clearer insight into which wallets are connected and their states on both `connect` and `disconnect`
=> [react-v2.2.6-alpha.2] : Enhancement - WalletState[] return to connect and disconnect hooks

packages/react/package.json
The previous React Package change had an out-of-date version and this prevented an Alpha package publish
=> [react-v2.2.7-alpha.1] : Fix - React package version update to publish Alpha version

.circleci/config.yml
=> Fix CI config for hw-common

packages/core/package.json, packages/core/src/index.ts, packages/core/src/views/Index.svelte, packages/dcent/src/index.ts, packages/demo/package.json, packages/react/package.json, packages/vue/package.json, yarn.lock
This change updates the logic around enabling and displaying notifications for the purpose of using customNotifications without needing an APIkey or any connected wallets
=> [core-v2.8.1-alpha.2] : Fix - Enable customNotifications without connected wallets or API key

packages/core/.eslintrc.cjs, packages/core/package.json, packages/core/src/replacement.ts
This PR fixes a typo that was causing the replacement UI to not display on notifications when initiated on a KeepKey wallet. Also added to the list of wallets that support replacement tx's is D'Cent wallet.
=> [fix]: Fixes typo

packages/torus/package.json
Lock torus dep version to last non-breaking change at `1.27.3` as `1.28.0` and later have changes to the API types cause build issues
=> [torus-v2.1.2-alpha.2] : Fix - Lock torus dep version

packages/core/src/index.ts
The query reference for the account center container element is not correct and will output `Element with query [object Object] does not exist`.
=> Fix error message for account center container element query reference

packages/walletconnect/package.json, packages/walletconnect/src/index.ts
#1271 
I console the requet method type in this file and found  the Incoming parameters is  eth_signTypedData_v4  when use  _signTypedData  method in ethers.js framework.
=> fix issue eth_signTypedData_v4 not supported

packages/core/package.json, packages/core/src/i18n/en.json, packages/core/src/views/connect/ConnectingWallet.svelte, packages/core/src/views/connect/Index.svelte
This PR fixes some edge cases that occur when connecting to MetaMask. If a connect request is made and the user clicks outside of the popup menu (which hides the login/connect popup), and then tries to connect again, the connect request will throw an error and Onboard will not be aware that there is another connect request in progress. This gets especially complicated when the `autoSelect` feature is used modals disabled as the app cannot know that the original request is hanging leading to a bad UX as outlined in #1279. This fix will work for any wallets that throw an RPC error for duplicate connect requests. As far as I am aware only MetaMask does this at this time.
The fix does the following:
- Ensures that only one connect request is in flight at any time. It does this via canceling …
=> [fix] - MetaMask Connect Flow

packages/core/package.json, packages/core/src/provider.ts, packages/core/src/types.ts
Currently, if a user were to connect multiple MetaMask accounts and then manually disconnect one of those accounts, the disconnected account will still appear connected in the internal `wallets` state and associated UI's driven by that state.
This change implements logic to handle this for wallets that support the `wallet_getPermissions` RPC method, which allows us to check which accounts are currently connected and compare them with our internal connected accounts state and then sync them.
Closes #1225
=> Enhancement: Sync accounts

docs/README.md
Replaced svelte README with a usable README
=> Docs readme updates

README.md, examples/with-ledger/README.md, packages/core/package.json, packages/core/src/validation.ts, packages/core/src/views/account-center/WalletRow.svelte, packages/demo/package.json, packages/demo/src/App.svelte, packages/gas/README.md, packages/react/package.json, packages/vue/package.json, yarn.lock
- Right align account balance and token within expanded AC
- Add validation for unique chain ID and error messaging around it
Old error message:
New error message:
=> [core, react, vue]: Fix - AC Expanded Balance Right Align & Chain ID validation and Error Message

packages/injected/src/types.ts
Add `isBitski` provider flag options as Bitski as isMetamask set to true
=> Add isBitski provider flag

packages/gas/package.json, packages/gnosis/README.md, packages/gnosis/package.json, packages/react/README.md, yarn.lock
Updated the Gas package.json to align with other packages.
Without this change the entire path is required when importing `@web3-onboard/gas` for the build to succeed
`import gasModule from '@web3-onboard/gas/dist/index.js'`
=> [gas-v2.1.4-alpha.1]: Fix - Update gas package to contain main and browser entry points

docs/package.json, docs/src/routes/__layout-homepage.svelte, docs/src/routes/__layout-kit-docs.svelte, docs/yarn.lock
Adds Algolia indexed searchability to our docs
Because the domain is exact matched we wont be able to see results until we push to prod(or setup a staging env)
Here is a search example from the Blocknative project page within the Algolia platform to show that the indexed pages are searchable and working as expected
=> Add Search to Docs

docs/src/lib/components/FeaturesSection.svelte, docs/src/lib/components/HeroSection.svelte, docs/src/routes/__layout-homepage.svelte, docs/src/routes/examples/connect-wallet.md
SEO updates to the homepage and connect wallet example page.
=> site seo content edits

docs/src/lib/components/gas/Gas.svelte
Add gas unsubscribe on destroy
=> Add gas unsubscribe on destroy

docs/src/lib/components/Footer.svelte, docs/src/routes/docs/[...1]overview/[...1]introduction.md, docs/src/routes/docs/[...1]overview/[...3]onboard.js-migration-guide.md, docs/src/routes/docs/[...2]getting-started/[...2]customization.md, docs/src/routes/docs/[...3]modules/common.md, docs/src/routes/docs/[...3]modules/core.md, docs/src/routes/docs/[...3]modules/gas.md, docs/src/routes/docs/[...3]modules/react.md, docs/src/routes/docs/[...3]modules/vue.md, docs/src/routes/docs/[...4]packages/common.md, docs/src/routes/docs/[...4]wallets/coinbase.md, docs/src/routes/docs/[...4]wallets/dcent.md, docs/src/routes/docs/[...4]wallets/formatic.md, docs/src/routes/docs/[...4]wallets/gnosis.md, docs/src/routes/docs/[...4]wallets/injected.md, docs/src/routes/docs/[...4]wallets/keepkey.md, docs/src/routes/docs/[...4]wallets/keystone.md, docs/src/routes/docs/[...4]wallets/ledger.md, docs/src/routes/docs/[...4]wallets/magic.md, docs/src/routes/docs/[...4]wallets/mew.md, docs/src/routes/docs/[...4]wallets/portis.md, docs/src/routes/docs/[...4]wallets/torus.md, docs/src/routes/docs/[...4]wallets/trezor.md, docs/src/routes/docs/[...4]wallets/walletconnect.md, docs/src/routes/docs/[...4]wallets/walletlink.md, docs/src/routes/docs/[...4]wallets/web3auth.md, packages/gas/README.md
- Updated the footer to include the privacy policy and the terms
- Created a "modules" & "wallets" section to differentiate between the 2
- Removed teh `@web3-onboard/` prefix from the modules
=> Re-org side menu + TOS in the footer

packages/sequence/README.md, packages/sequence/package.json, yarn.lock
As of sequence 0.43.0,  ethers is a peerDependency of sequence.
=> updated peerDependency of sequence package

packages/coinbase/package.json, packages/coinbase/src/index.ts
https://github.com/wagmi-dev/wagmi/issues/383, as discussed here, the coinbase wallet export constructor as default, and vite(or not caused by it) will wrap by another default. so we need to detect if the default export is the constructor. if not, use the next default.
=> [BUG] fix coinbase default entry

docs/src/routes/docs/[...4]packages/core.md
Add containerEl docs and update quickstart to remove deprecated chains and add new hot chains
=> Add containerEl docs and update quickstart to remove deprecated chains and add new hot chains

packages/core/package.json, packages/core/src/types.ts, packages/core/src/utils.ts, packages/react/package.json, packages/vue/package.json
It is impossible to run any array-specific methods on `chains` since typescript is not able to detect the array type correctly.
Example to reproduce:
```typescript
const onboard = Onboard(initOptions)
const chainId = defaultChainId ?? '0x1'
const chain: Chain | ChainWithDecimalId | null = initOptions.chains.find(
(chain: ChainWithDecimalId | Chain) => chain.id === chainId || chain.id === `0x${chainId.toString(16)}`
)
```
=> Change the typing of the chains

examples/with-nextjs-13/package.json, package.json, packages/core/package.json, packages/demo/package.json, packages/react/package.json, packages/torus/package.json, packages/uauth/package.json, packages/vue/package.json, packages/walletconnect/package.json, packages/web3auth/package.json, yarn.lock
- [core-v2.11.1-alpha.3, React, Vue]: Fix - Update README for CRA build, Added text color css vars to Action Req modal to align #1413 
- [Web3-Auth-v2.1.4-alpha.1, UAuth-v2.0.1-alpha.1, Core-v2.11.1-alpha.1, React, Vue]: Fix - Package Issues found during docs integration #1402 
- `@web3onboard/core` **v2.11.1**
- `@web3onboard/torus` **v2.2.0**
- `@web3onboard/web3auth` **v2.1.4**
- `@web3onboard/walletconnect` **v2.2.2**
- `@web3onboard/uauth` **v2.0.1**
- `@web3onboard/react` **v2.5.1**
- `@web3onboard/vue` **v2.4.1**
=> Release 2.15.1 (develop)

packages/demo/package.json, packages/injected/package.json, packages/injected/src/wallets.ts
Gamestop add a `0` before the numeric representation within single digit hex codes.
This fixes this issue
Example: `0x1` is `0x01` in Gamestop world which doesnt work W3O recognizing chains and styling them in AC
=> [injected-wallets: 2.5.0-alpha.2]: Fix - Gamestop chain recognition

packages/demo/package.json, packages/ledger/README.md, packages/ledger/package.json
Add Ledger docs for new init options
=> [ledger-v2.4.1-alpha.1]: Update - Add Ledger docs for new init options

docs/src/routes/docs/[...3]modules/core.md
First off all, I would like to give my appreciations to this project! Thanks for your work!
Just some small piece of missed documentation :sparkles:. I hope it will save some time for other developers :grinning: 
---
**_Are next points relevant for documentation?_**
=> docs: add a missing agreement to the appMetadata

packages/demo/package.json, packages/torus/package.json, packages/torus/src/index.ts
The Torus provider `chainChanged` event now returns a hex encoded string rather than decimal. The current patching logic does not handle hex encoded `chainId`. There is no need for the patch now, so this PR removes it.
Fixes #1446
=> Fix: Torus Chain Changed Error

packages/demo/package.json, packages/injected/package.json, packages/injected/src/index.ts
Prior to this fix if a different wallet had the `isMetaMask` flag set to true and MetaMask was available on the browser - MetaMask would be filtered out.
With the use of `otherProviderFlagsExist` function in the MetaMask `checkProviderIdentity` check (already in place) we check the MM provider against all other known wallet identity flags.
If no other flags exists besides the specified flag (`isMetaMask` in this case) we can safely assume the Wallet is MetaMask and we don't need other checks to filter it out.
One caveat of both approaches would be if an unknown (by W3O) wallet has `isMetaMask` set to true and injects at `window.ethereum` there will be a false positive. With W3O wallet coverage I think we are safe for the most part against this issue and users can find a way around or …
=> [injected-v2.6.0-alpha.4]: Fix - Filtering out MetaMask

packages/core/README.md, packages/core/package.json, packages/core/src/constants.ts, packages/core/src/index.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/core/src/validation.ts, packages/core/src/views/connect/Agreement.svelte, packages/core/src/views/connect/Index.svelte, packages/demo/src/App.svelte, packages/react/package.json, packages/vue/package.json
This PR implements a commonly requested feature for auto connecting a wallet that has been previously connected. There is now a `autoConnectLastWallet` option which can be set during initialization:
```javascript
const onboard = Onboard({
// ... other options
connect: {
autoConnectLastWallet: true
}
})
```
Also implemented in this PR is error handling for accessing `localStorage` to handle when browsers have blocked access (eg TOR browser).
=> Feature: Auto Connect Last Wallet Option

docs/yarn.lock, package.json, packages/core/package.json, packages/demo/package.json, packages/injected/package.json, packages/react/package.json, packages/transaction-preview/package.json, packages/vue/package.json
- Bump Wallet Connect version for alpha package out of canary #1528 
- Add Bifrost Wallet #1526 
- Update Transaction Preview Gas Used view - Add TP example to the Docs #1527 
- @web3-onboard/core: 2.15.1
- @web3-onboard/transaction-preview: 2.0.3
- @web3-onboard/injected-wallets: 2.8.0
- @web3-onboard/react: 2.6.3
- @web3-onboard/walletconnect: 2.3.0-alpha.2
- @web3-onboard/vue: 2.5.3
=> Release 2.20.1 (develop)

docs/package.json, docs/src/lib/services/onboard.js, docs/src/routes/docs/[...4]wallets/injected.md, docs/src/routes/docs/[...4]wallets/xdefi.md, docs/yarn.lock
XDEFI module was previously missing from the docs site and is added in this PR
=> Add XDEFI module and injected to docs site

docs/src/lib/components/ConnectWalletButton.svelte, docs/src/lib/components/ThemeCustomizer.svelte, docs/src/lib/components/examples/connect-wallet/ReactConnectWallet.md, docs/src/lib/components/getting-started-guide.md, docs/src/lib/services/onboard.js, docs/src/routes/docs/[...1]overview/[...1]introduction.md, docs/src/routes/docs/[...2]getting-started/[...2]theming.md, docs/src/routes/docs/[...2]getting-started/[...3]custom-styling.md, docs/src/routes/docs/[...3]modules/core.md, docs/src/routes/docs/[...3]modules/gas.md, docs/src/routes/docs/[...3]modules/react.md, docs/src/routes/docs/[...3]modules/transaction-preview.md, docs/src/routes/docs/[...3]modules/vue.md, docs/src/routes/examples/uniswap-widget.md, packages/core/README.md, packages/demo/src/App.svelte, packages/transaction-preview/README.md, packages/vue/README.md
Add theming docs, refine core init options, api actions and code chunks
=> Add theming docs, refine core init options, api actions and code chunks

docs/src/lib/services/onboard.js
Docs hot fix to temporarily remove Infinity wallet as it was breaking the connect button on the live docs site with the following error: 
```
Uncaught (in promise) TypeError: Failed to resolve module specifier "@web3-react/types". Relative references must start with either "/", "./", or "../"
```
=> Temporarily remove infinity wallet

packages/core/package.json, packages/core/src/disconnect.ts, packages/demo/package.json, packages/demo/src/App.svelte, packages/react/package.json, packages/vue/package.json
Remove wallet from localStorage when disconnect is called with the primary wallet label.
If a non-primary wallet is disconnected the localStorage will persist.
Closes: #1545
=> [core, react, vue]: Fix - Remove wallet from localStorage when disconnect is called with the primary wallet label

docs/package.json, docs/src/lib/services/onboard.js, docs/src/routes/docs/[...3]modules/core.md, docs/yarn.lock, examples/with-sveltekit/README.md, examples/with-sveltekit/package.json, examples/with-sveltekit/src/lib/web3-onboard.ts, examples/with-sveltekit/svelte.config.js, examples/with-sveltekit/vite.config.ts, examples/with-sveltekit/yarn.lock, packages/core/README.md
SvelteKit+Vite - Fix config issue with sveltekit and vite config - 
Update docs around this config and add links to examples
Adds context for to docs #1568
=> SvelteKit+Vite - Fix config issue with sveltekit and vite config - Add docs

docs/package.json, docs/src/routes/docs/[...4]wallets/walletconnect.md, packages/demo/package.json, packages/demo/src/App.svelte, packages/walletconnect/README.md, packages/walletconnect/package.json, packages/walletconnect/src/index.ts, packages/walletconnect/src/v2.ts, yarn.lock
This PR updates the `@walletconnect/ethereum-provider` packages to the latest and add a configurable `requiredChains` prop to the WC v2 initialization that defaults to `[1]`
This will allow dapps to define the required chains for supported wallets and was requested by @hlopes-ledger  one of the lead Ledger devs.
Documentation updates included!
```typescript
/**
* List of Required Chain(s) ID for wallets to support in number format 
* Hex is NOT CURRENTLY SUPPORTED for this property
* Defaults to [1] - Ethereum
* The chains defined within the web3-onboard config will define the
* optional chains for the WalletConnect module
*/
requiredChains?: number[] | undefined
```
=> [walletconnect-v2.3.1-alpha.1]: Update - walletConnect params to include `requiredChains` and updated WC deps

docs/src/routes/docs/[...1]overview/[...2]contribution-guide.md, pull_request_template.md
Updates PR template and Contribution Guide
=> Update PR template and contribution guide

docs/package.json, examples/with-ledger/package.json, examples/with-nextjs-13/package.json, examples/with-nextjs/package.json, examples/with-vite-react/package.json, examples/with-vuejs-v2/package.json, examples/with-vuejs/package.json, packages/core/package.json, packages/core/src/views/connect/Index.svelte, packages/demo/package.json, packages/react/package.json, packages/vue/package.json
Issue: https://github.com/blocknative/web3-onboard/issues/888
Stops calling selectAccounts when switching to an already connected wallet- stops displaying pop up that says "Please switch the active account in your wallet." 
[Testing Video](https://www.loom.com/share/573a1a75947e4dbc847ec0268466cea4)
- [NA] Add or update relevant information in the documentation
=> [core] Fix- Stop modal pop up when switching to already connected wallet

packages/core/README.md
- Fixed the title case `Buffer` injection, it solves the build issue (ie Netlify needs lowercase to build successfully)
- Added the missing `inject` function under the Vite environment section
=> fix: typo, missing inject fn in the documentation

docs/src/routes/docs/[...1]overview/[...1]introduction.md, docs/src/routes/docs/[...3]modules/core.md, packages/core/README.md, packages/core/package.json, packages/core/src/disconnect.ts, packages/core/src/index.ts, packages/core/src/types.ts, packages/core/src/validation.ts, packages/core/src/views/connect/Index.svelte, packages/demo/package.json, packages/demo/src/App.svelte, packages/react/package.json, packages/vue/package.json
Adds option to reconnect all previously connected wallets as an option.
Wallets will be reconnected in the order they were previously held within the array.
A new format is introduced within the PR for local storage saving of the wallet labels with an array of strings being used instead of a string. This will be the case regardless if the dev elects usage of `autoConnectAllPreviousWallet` or `autoConnectLastWallet`
```ts
type ConnectModalOptions = {
...
/** 
* If set to true, all previously connected wallets will store in 
* local storage. Then on init, onboard will try to reconnect to 
* each wallet with no modals displayed
*/
autoConnectAllPreviousWallet?: boolean
}
```
=> [core, react, vue]: Feature - Connect all previously connected wallets

docs/src/app.html
=> update favicon on docs site

packages/demo/package.json, packages/walletconnect/package.json, yarn.lock
Add peer dep required to run package outside of walletconnect eco: `"@web3modal/standalone":"^2.2.2"`
=> Add peer dep required

packages/demo/package.json, packages/trezor/package.json, packages/trezor/src/index.ts, yarn.lock
Will alleviate #1652 
Update to the latest Trezor package with a new naming pattern. 
All initialization options remains along with functionality.
Docs: https://www.npmjs.com/package/@trezor/connect-web
=> Update to the latest Trezor package deps

packages/react/package.json, packages/react/src/hooks/useAppState.ts
Fixes useWallets call mentioned in issue https://github.com/blocknative/web3-onboard/issues/1630
(Please ignore the typerror- it was coming from my frontier wallet extension)
Was this- returning whole state object: 
Now returns array (not state object):
=> Fix: getServerSnapshot call

docs/src/routes/docs/[...3]modules/react.md, packages/react/README.md, packages/react/package.json
Updates docs around usage of API key for react hooks package
Closes: #1666
=> Fix: Update react hooks docs re usage of apiKey

examples/with-vanilla-js/index.html, examples/with-vanilla-js/package.json, examples/with-vanilla-js/src/index.js, examples/with-vanilla-js/webpack.config.js
https://github.com/blocknative/web3-onboard/issues/1664
Fixes webpack-dev-server load files in index.html, walletconnect error, and accounts error on clicking away from connect
- [NA] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [NA] Add or update relevant information in the documentation
=> Fix Index.html script files and WalletConnect Error in Vanilla JS Example

.circleci/config.yml, packages/react/package.json, packages/web3auth/package.json
web3auth requires a node version of 16.18.1 but when adjusting only the node version within the docker container the .npmrc file is ignored. 
These updates should ensure the .npmrc is not ignored 🤞🏼
=> Fix: web3auth publish flow for latest deps

packages/core/package.json, packages/core/src/views/account-center/Minimized.svelte, packages/demo/package.json, packages/react/package.json, packages/vue/package.json, yarn.lock
Standardize the visualization of the chain icon within Account Center minimized and bring in line with Account Center Maximized. This handles icons imported outside of svg strings.
Handles discord issue shown here: https://discord.com/channels/542403978693050389/1050488289775321148/1107715492006862928
=> Fix: Account Center Minimized chain icon display standardization 

packages/core/package.json, packages/core/src/i18n/en.json, packages/core/src/views/connect/SelectingWallet.svelte, packages/core/src/views/connect/Sidebar.svelte, packages/core/src/views/shared/Warning.svelte, packages/demo/package.json, packages/react/package.json, packages/vue/package.json, packages/walletconnect/package.json, yarn.lock
Bump walletconnect deps to the latest
Remove unused import
Add missing values to Core i18n
=> Update: Bump WC deps to the latest & Add missing values to Core i18n

packages/demo/package.json, packages/walletconnect/package.json
Update to latest walletconnect packages for v1 depreciation
=> Upgrade wallet connect v2 packages

.circleci/config.yml, packages/arcana-auth/package.json, packages/arcana-auth/src/index.ts, yarn.lock
Fix arcana-auth circleci build
=> update arcana package and yarn

packages/arcana-auth/package.json, packages/arcana-auth/src/index.ts, yarn.lock
- [] send transaction
- [] switch chains
=> Update Arcana Auth SDK version

docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md
Changing order of offerings and adding themability to the top, removed SDK wallet list that was out of date & reference to subpages instead.
- [ x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x ] Check the box that allows repo maintainers to update this PR
- [ x] Test locally to make sure this feature/fix works
- [x ] Run `yarn check-all` to confirm there are not any associated errors
- [x ] Confirm this PR passes Circle CI checks
- [x ] Add or update relevant information in the documentation
- [x ] Add/update the appropriate package README (if applicable)
- [ x] Add/update the related module in the [docs …
=> Update bullets, removing SDK wallets

docs/src/routes/docs/[...4]wallets/[...11]injected/+page.md, packages/demo/package.json, packages/injected/package.json, packages/injected/src/constants.ts, packages/injected/src/icons/subwallet.ts, packages/injected/src/types.ts, packages/injected/src/wallets.ts
**Add SubWallet wallet into web3-onboard.**
SubWallet is the comprehensive non-custodial wallet solution for Polkadot, Substrate & Ethereum ecosystems. With the mission of bringing users closer to Web3, we envision a Web3 multiverse gateway through which users can enjoy multichain services with utmost ease and absolute security. Connecting and using blockchain-based applications is smoother than ever with SubWallet Browser Extension & SubWallet Mobile App.
The provider is available on window.SubWallet.
=> Feat/add SubWallet wallet

docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md
added link that was missing for quickstart & updated to Web3 Onboard.
- [ x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
=> Add link & update nomenclature

docs/src/routes/docs/[...3]modules/[...1]core/+page.md, docs/src/routes/docs/[...4]wallets/[...11]injected/+page.md, packages/core/README.md, packages/core/package.json, packages/core/src/constants.ts, packages/demo/package.json, packages/injected/README.md, packages/injected/package.json, packages/injected/src/wallets.ts, packages/react/package.json, packages/vue/package.json
Update the Tx_boost (transaction protection) to the non-alpha url
Update OKX wallet to be available on all devices - Closes: #1900
=> Update - Tx Boost URL to non-alpha, OKX wallet available on all devices

packages/demo/package.json, packages/torus/package.json, packages/torus/src/index.ts, yarn.lock
Update @toruslabs/torus-embed version
addresses https://github.com/blocknative/web3-onboard/issues/1935
- [NA] Add or update relevant information in the documentation
=> Update @toruslabs/torus-embed version

.circleci/config.yml, docs/package.json, package.json, packages/demo/package.json, packages/torus/package.json
- **Update @toruslabs/torus-embed version #1936**
- **Bump postcss from 8.4.6 to 8.4.31 #1938**
- **Bump postcss from 8.4.21 to 8.4.31 in /examples/with-vuejs #1939**
- **Bump postcss from 8.4.24 to 8.4.31 in /examples/with-vite-react #1940**
- **Bump postcss from 8.4.23 to 8.4.31 in /docs #1941**
- **Bump postcss from 8.4.21 to 8.4.31 in /examples/with-sveltekit #1942**
- **Bump postcss from 8.4.19 to 8.4.31 in /packages/demo**
@web3-onboard/torus: 2.2.6
=> Release 2.24.13 (develop)

docs/src/routes/docs/[...3]modules/[...4]solid/+page.md
Solid module docs code block handling update to `typescript` instead of `tsx`
=> Fix: Solid module docs code block handling

docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md, docs/src/routes/docs/[...3]modules/[...4]solid/+page.md, docs/yarn.lock, packages/demo/package.json, packages/metamask/package.json, packages/metamask/src/index.ts
This PR updates the handling of the MetaMask import to be handled properly in server envs.
It also adds MetaMask to a docs list of wallets supported
=> Update - MetaMask module handling in node envs, update docs

docs/package.json, docs/src/routes/docs/[...1]overview/[...1]introduction/+page.md, docs/src/routes/docs/[...3]modules/[...4]solid/+page.md, docs/src/routes/docs/[...4]wallets/[...18]metamask/+page.md, docs/yarn.lock, packages/demo/package.json, packages/metamask/README.md, packages/metamask/package.json, packages/metamask/src/index.ts, yarn.lock
Metamask sdk version bump, small patch to fix autoconnecting issue, docs update
=> Fix - Metamask sdk version bump, small patch to fix autoconnecting issue, docs update

docs/package.json, packages/cede-store/package.json, packages/demo/package.json, yarn.lock
Upgrade @cedelabs/providers dependency to 1.5.
=> feat: upgrade @cedelabs/providers to 1.5

packages/demo/package.json, packages/ledger/package.json, packages/ledger/src/v1.ts, packages/ledger/src/v2.ts, yarn.lock
Loads [@ledgerhq/connect-kit](https://www.npmjs.com/package/@ledgerhq/connect-kit) package via package manager instead of via @ledgerhq/connect-kit-loader (which is deprecated). 
This latest version of @ledgerhq/connect-kit that is now imported fixes this issue: https://github.com/blocknative/web3-onboard/issues/1996
=> load ledger connect kit via package instead of loader

packages/core/package.json, packages/core/src/views/connect/WalletButton.svelte, packages/demo/package.json, packages/react/package.json, packages/solid/package.json, packages/vue/package.json
Updated `WalletButton` font-size to use css vars instead of a hardcoded value.
- Resolves #2060
- Bumped core version from `2.21.2` → `2.21.3-alpha.1`
- Bumped core version for dependents
- `packages/demo`
- `packages/react`
- `packages/vue`
- `packages/solid`
=> fix: use css vars for font size (wallet button)

examples/with-sveltekit/package.json, examples/with-sveltekit/svelte.config.js, examples/with-sveltekit/vite.config.ts, examples/with-sveltekit/yarn.lock
Updated vite.config, imports and svelte.config to run the project properly
=> Fix the Sveltekit demo

.circleci/config.yml
Update Node version in build for Trezor: 18.19.1 & Keepkey to 16.20.2
=> Update Trezor & Keepkey build node v to 18

.circleci/config.yml
Keepkey build Node version to 16.20.2 which is causing build errors
=> [FIX] -  Keepkey build Node version to 16.20.2

.circleci/config.yml, packages/demo/package.json, packages/metamask/package.json, yarn.lock
=> Bump MetaMask module sdk deps

.circleci/config.yml
Update node version for metamask within CCI to 18.19.1
=> Update node version for metamask within CCI to 18.19.1

packages/core/src/preflight-notifications.ts, packages/gas/README.md
=> chore: fix typos and link broken

docs/src/routes/docs/[...4]wallets/[...5]capsule/+page.md, packages/capsule/package.json, packages/capsule/src/types.ts, packages/demo/package.json
=> Update Props to be Partial

packages/core/package.json, packages/core/src/connect.ts, packages/core/src/disconnect.ts, packages/core/src/index.ts, packages/demo/package.json, packages/demo/src/App.svelte, packages/react/package.json, packages/solid/package.json, packages/vue/package.json
Handling of empty localStorage item, remove default of empty string and perform a falsey check.
Ensure that if an empty `connect` config object is passed and the user doesnt have a localStorage wallet set as the last used then handle check for the last connected wallet properly.
Also properly handles empty object passed in through `connect({})`
Closes: #2227 
Closes: #2237
=> [FIX] : CORE - Handling of empty localStorage item, remove default of empty string and perform a falsey check

packages/demo/package.json, packages/metamask/package.json, yarn.lock
Update metamask deps to `@metamask/sdk`: `0.20.5`
=> Update metamask deps to `@metamask/sdk`: `0.20.5`

packages/demo/package.json, packages/metamask/package.json, yarn.lock
Update the metamask-sdk package to version '0.26.1'
=> chore: update the 'metamask-sdk' package to version '0.26.1'

docs/src/lib/services/onboard.js
Updated the `clientID` and `redirectUri` within uauthOptions for the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) to fix the invalid redirect URI issue on https://onboard.blocknative.com/examples/connect-wallet
=> Fix: updated uauthOptions in docs demo

docs/package.json, packages/capsule/README.md, packages/capsule/package.json, packages/demo/package.json, packages/demo/src/App.svelte, yarn.lock
- Update @usecapsule/wagmi-v2-integration to latest version
- Update @usecapsule/react-sdk to latest version 
- Refresh Capsule README.md.
These updates ensure compatibility with latest Capsule SDK features and security patches.
=> feat(deps): upgrade Capsule SDK dependencies

packages/injected/src/helpers.ts, packages/injected/src/wallets.ts
helpers.ts:
```js
-    return !!provider.providers?.some(provider => checkProviderIdentity({ provider, device }));
+    return Array.isArray(provider.providers) && !!provider.providers.some(provider => checkProviderIdentity({ provider, device }));
```
wallets.ts:
```js
-    checkProviderIdentity: ({ provider }) => !!provider && !!provider['ethereum'][ProviderIdentityFlag.Bitget],
+    checkProviderIdentity: ({ provider }) => !!provider && !!provider['ethereum'] && !!provider['ethereum'][ProviderIdentityFlag.Bitget]
```
=> Add null check to prevent potential runtime errors

.circleci/config.yml, .github/workflows/pr-status-checks.yml, packages/trezor/package.json, yarn.lock
Hello from Trezor,
We noticed that you are using an older version of the @trezor/connect-web library, which we are planning to deprecate in the upcoming months.
This PR updates it to the latest version to ensure continued compatibility.
=> Bump @trezor/connect-web to version 9.5.0

packages/core/package.json, packages/core/src/views/connect/Sidebar.svelte
=> Feature: Add link to thirdweb logo

.github/workflows/node-production.yml, .github/workflows/node-staging.yml
This pull request introduces two new GitHub Actions workflows to automate the release process for Node.js packages. One workflow handles production releases for the `main` branch, while the other manages staging (alpha) releases for the `develop` branch. These workflows streamline the build, test, and publish processes for multiple packages with specific Node.js versions.
* Added `.github/workflows/node-production.yml` to handle production releases triggered by pushes to the `main` branch. The workflow builds and publishes packages to npm with the `latest` tag, skipping alpha versions.
* Added `.github/workflows/node-staging.yml` to handle staging releases triggered by pushes to the `develop` branch. The workflow builds and publishes alpha versions of packages to npm with the `next` tag, …
=> Setting up GitHub CI for packages

.github/workflows/node-production.yml, .github/workflows/node-staging.yml
This pull request updates the GitHub Actions workflows for both production and staging environments to use specific commit SHAs for action versions, ensuring stability and reproducibility. The changes affect the `checkout`, `setup-node`, and `cache` actions.
* `.github/workflows/node-production.yml`:
- Updated `actions/checkout` to use commit SHA `11bd71901bbe5b1630ceea73d27597364c9af683` (v4.2.2).
- Updated `actions/setup-node` to use commit SHA `49933ea5288caeca8642d1e84afbd3f7d6820020` (v4.4.0).
- Updated `actions/cache` to use commit SHA `5a3ec84eff668545956fd18022155c47e93e2684` (v4.2.3).
* `.github/workflows/node-staging.yml`:
- Updated `actions/checkout` to use commit SHA `11bd71901bbe5b1630ceea73d27597364c9af683` (v4.2.2).
- Updated `actions/setup-node` to use commit SHA …
=> Pin github ci version
